### ISSUE TITLE
php5-intl is a requirement

### ISSUE THREAD

**Issue by rolfdeenen** [xenocrat/chyrp-lite#10]
Hi. I want to install chyrplite on my raspberry pi with a variant of Raspbian installed (osmc). I get an error: "Call to undefined function locale_get_default()". It seems php5-intl must be installed as a requirement. Perhaps this should be added to the documentation? I ran "apt-get install php5-intl" which made the error disappear.

**Comment by xenocrat** [comment]
Thanks for the report! I will add a test for the extension and only use it if available.

**Comment by dahliadahlia** [comment]
Wanted to chime in and report / confirm the requirement. Unable to use in a shared environment so far. Thanks for fixing this in a future release. :)

**Comment by xenocrat** [comment]
2016.01 has been [released](https://github.com/xenocrat/chyrp-lite/releases/tag/v2016.01) with a fix for this issue.
