### ISSUE TITLE
Like module doesn't work on musl-based systems

### ISSUE THREAD

**Issue by jpalczewski** [xenocrat/chyrp-lite#100]
Hello there,

If likes module  is enabled, entering the like tab throws an error:
`Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE' (this will throw an Error in a future version of PHP)`
This kind of error is caused possibly by musl library that powers alpine linux, so its rather known one: https://github.com/zendframework/zend-stdlib/issues/58
If long-terms plan assume docker version of chyrp, it would be nice to have any fallback for it.

**Comment by jpalczewski** [comment]
Edit: syntax highlighting also fails in similar way, btw.

**Comment by xenocrat** [comment]
Hello there.

Thanks for the report. I will look into rewriting this code using a DirectoryIterator instead.
