### ISSUE TITLE
How to post a question on Chyrp?

### ISSUE THREAD

**Issue by supersophie** [xenocrat/chyrp-lite#101]
Hi,

I cannot find the mailing list for Chyrp.  I looked on github and googled and had no luck. However, I do receive emails from chyrp termed as Conversations, but I cannot interact with these. 

 How can I post a question about Chyrp?

thanks, So

**Comment by xenocrat** [comment]
There is no mailing list for Chyrp Lite. You have "watched" this repository using the button at the top of this web page. If you are on the Github website as you read this text, click on the "Unwatch" button and choose your preferred level of communication.

**Comment by supersophie** [comment]
Hi, 
OK this is a pity. 
Regardless I  don't want to Unwatch. The level of communication was just fine as it was and helped me out on a few occasions.   

Are there any other places for support known?

**Comment by xenocrat** [comment]
You can use this project's Github issues tab to ask questions and request enhancements, either by commenting on an existing issue or by opening a new issue.
