### ISSUE TITLE
Installation error: ERROR: Database error: ..... error in your SQL syntax

### ISSUE THREAD

**Issue by csjjpm** [xenocrat/chyrp-lite#103]
Hi,
  I am trying to install your blog software.  I am running on FreeBSD with Apache 2.4, MySQL 8.0.1x, PHP 7.2.  I've set the folder permissions.  I created a table in my database and get this error when I try install.php
  I've tried to create the database as utf8_general_ci and utf8mb4_unicode_ci but neither makes a diference.
ERROR: Database error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups ( id INTEGER PRIMARY KEY AUTO_INCREMENT, ' at line 1 Query String CREATE TABLE IF NOT EXISTS groups ( id INTEGER PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) DEFAULT '', UNIQUE (name) ) DEFAULT CHARSET=utf8 Parameters Array ( )

**Comment by xenocrat** [comment]
Hello there.

Thanks for the report and sorry that you had an issue. It seems that MySQL 8+ has added “group” to the list of [reserved words](https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-new-in-current-series) so I will need quote it in all queries.

This will definitely get fixed but it will take me a few days to plan and implement it in the best possible way. In the meantime, your options are to downgrade to MySQL 7.x or wait for the fix.

**Comment by xenocrat** [comment]
Another workaround is to try installing with a table prefix (by entering some text like “blog” in the optional field on the installer page). It will result in the creation of a table called “bloggroups” and MySQL should be happy with this.
