### ISSUE TITLE
Support request:  Cannot create a "Post" entry

### ISSUE THREAD

**Issue by supersophie** [xenocrat/chyrp-lite#106]
Hi,

It's been a while since I created a post on chyrp. After several hours I have had to resort to raising my hand for help!

The chyrp lists these items for posts "Page Text Quote Photo Uploader Link", so I wrote a Page. Except the Page is not a Blog post :(  I cannot see anywhere I can get an actual Blog post.

I looked under Manage, and it shows Posts and Pages etc.
"Posts Pages Users Groups Migration Tags Import Export"
I tried editing the Page hoping I could change the type to a Post, but no such luck.

Any ideas how we create a Post these days?

Thanks

S.

**Comment by xenocrat** [comment]
Hello there.

Please read the relevant section of the [Quick Start Guide](https://github.com/xenocrat/chyrp-lite/wiki/Quick-Start-Guide#using-your-blog) and the [glossary of terms](https://github.com/xenocrat/chyrp-lite/wiki/Glossary-of-Terms). You'll notice that [Page](https://github.com/xenocrat/chyrp-lite/wiki/Glossary-of-Terms#page) is not a type of blog post. Text, Quote, Photo, Uploader, and Link are [feathers](https://github.com/xenocrat/chyrp-lite/wiki/Glossary-of-Terms#feather) that enable Chyrp Lite to support different types of content in blog posts.
