### ISSUE TITLE
ERROR: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by Latz** [xenocrat/chyrp-lite#109]
While installing with PHP 7.4.3:

ERROR: Trying to access array offset on value of type null

Installing with PHP 7.3 works flawlessly. 

Edit: Just realized that there's an error_log.txt:
ERROR: 8 Trying to access array offset on value of type null (/home/latz/www/chyrp/includes/class/Query.php on line 115)

**Comment by xenocrat** [comment]
Thanks for the report. I’ll investigate.

**Comment by Latz** [comment]
😎
