### ISSUE TITLE
Unwanted smiley rendered when writing: =d 

### ISSUE THREAD

**Issue by rolfdeenen** [xenocrat/chyrp-lite#11]
Hi. I just wrote a text containing the line: `SELINUX=disabled` . This gets rendered as SELINUX😃isabled . Is suppose that rendering of smileys should not occur in code blocks?

Regards,
Rolf

**Comment by xenocrat** [comment]
Extra parsing would be required to detect and avoid code blocks. Right now the filter is a very simple and fast string replacement.

I will give some thought to the problem. Thanks for the report.

**Comment by mtech** [comment]
It's because of the XD that is standard for making smiley face. Just put a space in between SELINUX Disabled. Problem solved.

**Comment by xenocrat** [comment]
I did discover a bug in the emoji code, which caused =d to be converted into an emoticon. It should be that only =D is converted but the replace function was case insensitive, causing it to convert =d as well – I've now fixed this.

**Comment by kreativmind** [comment]
Please close this issue since it's fixed @xenocrat. Thanks

**Comment by xenocrat** [comment]
I'm going to keep it open until the next release because there is actually a bug here ("=d" converted to emoji when only "=D" should be converted) as well as a feature request.

**Comment by kreativmind** [comment]
Ahh...okay. I didn't try it out so I wouldn't have known. This seems to be so because the smiley face =D and =d are read as the same regardless of case.

**Comment by kreativmind** [comment]
@xenocrat Any time frame on a new release? No rush...just curious. Thanks.

**Comment by xenocrat** [comment]
Very soon. Targeting late Jan / early Feb.

**Comment by xenocrat** [comment]
2016.01 has been [released](https://github.com/xenocrat/chyrp-lite/releases/tag/v2016.01) with a fix for this issue.

**Comment by kreativmind** [comment]
Thanks brother!
