### ISSUE TITLE
cacher: Creating new file for every post request

### ISSUE THREAD

**Issue by neelchauhan** [xenocrat/chyrp-lite#113]
I recently set up Chyrp Lite on FreeBSD 12.1 with Apache, and whenever I do a benchmark on a post, `cacher` creates a new file for each request instead of using the previously cached version. Pages and the front page do not have this issue.

This happens on `wrk` and `ab`.

    root@rainpuddle:/usr/local/www/www.neelc.org/includes/caches/html # ab -n 1000 -c 100 https://www.neelc.org/2019/12/25/a-simple-ipfw-in-kernel-nat-setup-on-freebsd/
    ...
    root@rainpuddle:/usr/local/www/www.neelc.org/includes/caches/html # ls | wc
        1000    1000   46000
    root@rainpuddle:/usr/local/www/www.neelc.org/includes/caches/html #

**Comment by xenocrat** [comment]
Hello there.

The cacher module does caching on a per visitor per session basis, so you would need to supply a session cookie (e.g. using the ab option -C ChyrpSession=foobar) for the module to recognise you and serve you a previously generated cache file. Without the cookie, a new session ID is generated for you each time. I can’t explain why you are not seeing this behaviour on some pages; it should be true everywhere.

You can see how the unique cache ID is constructed [here](https://github.com/xenocrat/chyrp-lite/blob/master/modules/cacher/cacher.php#L17).
