### ISSUE TITLE
Sorting posts old --> new / new --> old

### ISSUE THREAD

**Issue by carforge** [xenocrat/chyrp-lite#114]
Hi.

Is there a possibility to change the sorting of the blog posts?
Currently there is always the newest entry on top (or below the pinned posts). I would like to have it the other way around. Pinned and then old to new.

Thanks!

**Comment by xenocrat** [comment]
Hello there.

There's no built-in option for changing the post ordering, but it can be done. How you do it depends on how extensive you want the reordering to be.

### Option 1

You can create a module to overload the index and order it as desired. This is the most maintainable solution, but it only affects the main blog index. You can read the instructions for creating a simple module [here](https://github.com/xenocrat/chyrp-lite/wiki/Making-Your-First-Module), and below is the code your module would contain:

    <?php
        class ReverseIndex extends Modules {
            public function main_index($main) {
                $main->display("pages".DIR."index",
                               array("posts" => new Paginator(Post::find(
                               array("placeholders" => true,
                                     "order" => "pinned DESC, created_at ASC, id ASC")),
                                     $main->post_limit)));
            }
        }

### Option 2

If you want to change the default ordering everywhere, you can edit [_includes/model/Post.php_](https://github.com/xenocrat/chyrp-lite/blob/493723e765f7600b7d1fd36b4419a10cb1d1816e/includes/model/Post.php#L156), but this will have some weird effects, for example your feeds for searches, categories, and tags will be stuck showing the oldest items. You will also need to reimplement this after you install a Chyrp Lite update.

**Comment by carforge** [comment]
Hello.

Thanks for this perfect answer. Sadly the module is not working.
Uploaded the php file and activated the module. But the posts are still ordered from new to old. :/

**Comment by carforge** [comment]
Hello.

Thanks for this perfect answer. Sadly the module is not working.
Uploaded the php file and activated the module. But the posts are still ordered from new to old. :/

**Comment by carforge** [comment]
Hello.

Thanks for this perfect answer. Sadly the module is not working.
Uploaded the php file and activated the module. But the posts are still ordered from new to old. :/

**Comment by carforge** [comment]
Hello.

Thanks for this perfect answer. Sadly the module is not working.
Uploaded the php file and activated the module. But the posts are still ordered from new to old. :/

**Comment by xenocrat** [comment]
That's strange. I tested the code and it's working as intended for me. Enabling [debug mode](https://github.com/xenocrat/chyrp-lite/wiki/Debug-and-Tester-Modes) is useful to troubleshoot module problems, because some types of module errors are suppressed otherwise.

**Comment by thethinkingman** [comment]
carforge:

The code that xenocrat typed works... but I think with one modification it might get closer to what you are after.

The only downside is that the pinned items will be at the top BUT ordered by the oldest creation date first -- as with your other posts

Try changing the order by to:

"order" => "pinned DESC, created_at ASC")),

So you will end up with -- Pinned and then old to new. The only thing is (as I said) the Pinned items will be at the top but sorted from oldest to newest.
