### ISSUE TITLE
Install on localhost (old but new)

### ISSUE THREAD

**Issue by RolandTi** [xenocrat/chyrp-lite#115]
Hello,
I'm trying to install the last chyrp on a local machine (with mamp),
but I can't to it because of the url : http://localhost/chyrp
I'm getting : "Invalid Chyrp URL."

The same thing happened, I know, in 2018. 
I'm trying with both php 7.3.9 & 7.4.1

Is it ok for you ?

**Comment by xenocrat** [comment]
Hello there.

This is on purpose. In almost every case that is not a local test rig, entering localhost as IP address is a mistake or an attempt by a hostile user to do something malicious. The URL sanity check accepts IPv4, IPv6, and domain names. It rejects localhost and any scheme other than http/s (e.g. “javascript:” is rejected).

Enter the local IP address of your computer when installing and all will be well.
