### ISSUE TITLE
A few development questions

### ISSUE THREAD

**Issue by thethinkingman** [xenocrat/chyrp-lite#118]
Hi Admins,
1) Locales - Can you point me to some reference doco? I see the references in the modules main files but the format of the locale is foreign to me. Like, does referencing the line numbers actually do anything? or is it for reference?

2) Writing errors - I admit I haven't looked into this .. except that I have noticed an 'error' routine somewhere and errors get stored in error_log.txt. How can I utilize them? i.e. in the reCaptcha module, if there is an error connecting to Google it might be good to log the error code.

Not many questions. So far it is easy to develop for.

BTW:
I have developed a SimpleMDE module (SimpleMDE is a simple, embeddable, and beautiful JS markdown editor).
It works really nice. I will make it available once I understand the above and incorporate it into the code.

**Comment by xenocrat** [comment]
Hello again.

You can find some documentation for the locale functions in [Localizing Extensions](https://github.com/xenocrat/chyrp-lite/wiki/Localizing-Extensions) and some broader documentation in [Introduction to Translations](https://github.com/xenocrat/chyrp-lite/wiki/Introduction-to-Translations). The translation format is GNU gettext.

If you want to throw a hard error use the function [`error()`](https://github.com/xenocrat/chyrp-lite/blob/master/includes/error.php#L64). This is called whenever an error or exception is caught, but you can also call it directly. Be aware that this will report the error and then end execution immediately, so it’s best avoided for recoverable errors.

For soft errors you can use the [Flash](https://github.com/xenocrat/chyrp-lite/blob/master/includes/class/Flash.php) class to display a warning to the user. Chyrp Lite generally tries to do this for errors encountered on the visitor-facing blog pages. You’ll see Flash being used a lot in MainController.

You can use the PHP function `error_log()` to log without throwing an error, but in that case it’s best to make your logging conditional on the constant `DEBUG` to avoid bogging down production environments with excessive logging.

I hope that helps!

**Comment by xenocrat** [comment]
An additional note: you can make use of the differing error reporting levels between production and `DEBUG` modes to trigger errors that will cause a hard stop during development (good for debugging) but not when encountered on a live site.

This code will trigger an error that is only reported in debug mode:

    trigger_error($message, E_USER_NOTICE);

**Comment by thethinkingman** [comment]
Awesome. Thanks for the info.

I have downloaded Poedit and will give it a go for the locales.

I will have a play today, and will change the error handling and locales in my modules too.
