### ISSUE TITLE
Chirp Lite Logo

### ISSUE THREAD

**Issue by thethinkingman** [xenocrat/chyrp-lite#119]
I am not sure if you are interested but I came up with this... maybe for a logo or something.

If you don't use it/them I won't mind. I had some time and wanted an image for my websites blog post.

![chirp-lite-logo](https://user-images.githubusercontent.com/10008548/95324919-2d491380-08ec-11eb-9fc5-1e20532c3366.png)

If you are interested then I can send you the PSD.

**Comment by xenocrat** [comment]
Thank you for the kind offer but I prefer to remain unbranded so that people don't mistake this little project for a product and set their expectations too high. I must say, that bird is nicely done!

**Comment by thethinkingman** [comment]
All good. Fair point.
Yeah I like how the vibrant colours came out.
