### ISSUE TITLE
Propose Version inside of General Settings

### ISSUE THREAD

**Issue by thethinkingman** [xenocrat/chyrp-lite#120]
I didn't see the Chyrp Lite version listed anywhere inside of the Admin area.

I didn't know if I downloaded the latest version and could only find it in the source.

I was wondering if it is a good idea to have the version listed in the General Settings page.

**Comment by xenocrat** [comment]
Good idea. Implemented. :-)

**Comment by thethinkingman** [comment]
Super. That'll be handy.
I'm just working on my theme now. Just playing around with ideas.
