### ISSUE TITLE
Curiousity about Pages/index.twig

### ISSUE THREAD

**Issue by thethinkingman** [xenocrat/chyrp-lite#121]
I was just going through the files looking for something and noticed that the "end for" is within the second ELSE.

Is that right? I would expect it to be within the first part of the IF. Could just be my lack of understanding of TWIG.
```
{% block content %}
    {% if reason is not defined %}{# Some modules define reason in error states #}
        {% for post in posts.paginated %}
            {% include(["feathers" ~ DIR ~ post.feather ~ ".twig", "feathers" ~ DIR ~ "missing.twig"]) %}
    {% else %}
        <div class="ribbon">
            <h3 class="ribbon">{{ "No posts" | translate }}</h3>
        </div>
        {% endfor %}
    {% else %}
        <div class="ribbon">
            <h3 class="ribbon">{{ reason }}</h3>
        </div>
    {% endif %}
{% endblock %}
```

**Comment by xenocrat** [comment]
Twig allows `else` to be used inside the `for` loop to [define a block to render](https://twig.symfony.com/doc/1.x/tags/for.html#the-else-clause) if `posts.paginated` is empty.

**Comment by thethinkingman** [comment]
Wow. Well you learn something new each day. That's a very interesting concept. Thanks.
