### ISSUE TITLE
Request to have longform class added to article element in themes

### ISSUE THREAD

**Issue by thethinkingman** [xenocrat/chyrp-lite#122]
Hi,
(Me again, sorry to be a pain)

I would like to have the class longform added to post.php article element in the themes.

```<article class="post {% if post.body | length > 1000 %} longform{% endif %} {{ post.feather }}{{ post.pinned ? ' pinned' : '' }}" id="post_{{ post.id }}">```

I believe that it will make it easier for future users to style the articles in their themes -- when in short and/or long form.

Obviously the code above is an example... and probably not a good solution as it only does longform when the length is greater than 1000... and some articles may not reach that limit.  But you get the idea.

For example:

In my theme, the articles on my "home" page are displayed in a specific way. I am actually turning the Section into a Grid so that I can position the elements all over the place.

Obviously, when viewing the full (longform) article the layout will be different.

At the moment I can only do this to prevent the "home" page styles from working:

```
article section.body:not(.longform) h2 {
font-size: 18px;
}
```

I cannot do that on the footer because it has nothing that distinguishes it from being displayed in short form or long form.

The answer could be to add longform to the footer element... but I think that adding it to the article element will cover all bases.

Obviously the preference would be to remove the longform class from the section element too... but all of the themes would need to be modified to reflect the change - if they use the longform class.

I have modified my own theme.. but I think that it will be good for others.

Thanks

**BTW:** My website is www.thethinkingman.com.au is you want to check it out. The dynamic menu etc is done by CSS. The GoToTop button (bottom right) uses a tiny bit of javascript. I'm just now working on the longform view of the posts.

**Comment by xenocrat** [comment]
Hello there. Nice website!

If I understand correctly, the problem you want to solve is that you want to be able to tell if a post is being viewed standalone or as part of a blog stream (for example the index or the stream of all posts in a category) and you want to style it differently based on that.

I've added some code to each theme that will make the route action a class of the HTML body. If you want to style a post differently when it is being viewed standalone using one of the bundled themes, you'll soon be able to use the CSS rule `body.route_view article.post` to target it. If you want to change the styling just on the index you'll be able to use `body.route_index article.post` instead.

Thanks for mentioning the `longform` section classes. They are leftovers from an old unimplemented idea which I will remove now I've been reminded about them.

**Comment by thethinkingman** [comment]
You understood exactly.

That'll work.

Thank you once again.
