### ISSUE TITLE
Title 403 Error

### ISSUE THREAD

**Issue by thethinkingman** [xenocrat/chyrp-lite#126]
For a title of a Post (TEXT) I typed: **Javascript: Floating Text**, added some content, and Saved.

I received a nice 403 error.

Typing: **Jason: Floating Text** works

Typing: **Javascript Floating Text** works 

Typing: **Javascript: Floating Text** doesn't work

Obviously Javascript: is causing something to go whammy -- but it should be handled better.

Not a big deal or anything.. I just changed the title (excluded the : )

**Comment by xenocrat** [comment]
Hello there.

I can't reproduce this, and there is no code in Chyrp Lite to produce a 403 if "javascript:" is detected in a post title. What might well be happening is that your web host has some anti-XSS feature that is is scanning POST requests and denying those that look suspicious. I had a similar problem with an over-zealous web host responding with 403 if it detected "http:" in a POST request, which is the reason Chyrp Lite will accept URLs without a scheme.

**Comment by thethinkingman** [comment]
I will look into it further. I will keep this open for a little bit.

**Comment by thethinkingman** [comment]
You are correct.

I created a quick html file with an input and a submit and it does the same thing.

I momentarily changed my htaccess to disable security filtering (SecFilterEngine Off) and it worked.

I have never run into that before. Good to know.

Thanks
