### ISSUE TITLE
Related Posts module and admin config extension query

### ISSUE THREAD

**Issue by michaelwylde** [xenocrat/chyrp-lite#127]
I was going to try my hand at creating a related_posts module, when creating or editing a post it would allow a selection of currently available posts from a dropdown (with potential searching functionality). This list would then appear after the post (or in another related_posts section as dictated by the theme). 

After looking at some triggers I noticed that the theme class has a section for related_posts that is currently only populated by the tag and categorize modules. These add the ID to an array with a FIFO ordering, so I would need to make sure my module runs first using the priority system. However I cannot see a way for my module to skip over or cancel the effect of the listeners inside tag and categorize in the event that my module inserts less then the limit.

I have two options - I could set my module priority to last, clear the ids array and add mine in, this does mean unnecessary queries are being run by the tag and categorize modules but would work. 
The other cleaner option would be to add two configs to disable tag and categorize from adding to the related_posts array. My first thought was to make this a config in the related_posts module but then it seems to make more sense to simply add this into the tag and categorize modules themselves as the logic to exclude the trigger would need to be in there anyway.

I was thinking of adding the settings to: "Admin > settings > content" including another config to adjust the limit to 3.

I am happy to make the changes and contribute it back if you think this is something you may want to include however I need some advice on where you think this works best. 

I can set the config default in the upgrade scripts, however I cannot seem to find a way to add the config setting to the admin so it is editable in the UI without editing the admin controller and associated admin/page/*.twig file. I could add a trigger into the admin_content_settings which would allow me to save the config in my own module but I am not too sure the best way to approach the twig extension.
If the best solution is to have a new tab per module (similar to admin_sitemap_settings) then I guess that works - was just worried it might mean lots of tabs with only a few settings each.

Thanks for any advice in advance and apologies if I missed something in the wiki that explains the above.

**Comment by xenocrat** [comment]
Hello there.

I’m very wary about any changes requiring more UI unless absolutely necessary.

I think it makes perfect sense for you to prioritize your trigger so it runs before tags and categorize; a related post specifically selected by the user clearly has greater relevance and should appear at the top of the list. I’ll do what I should have done in the first place and modify the responders in tags and modules to return immediately if the post limit has already been reached, so there won’t be wasted queries.

The post limit is decided by the Theme, so I prefer to keep it as a setting people can modify by digging into the theme templates and modifying the number there. Once I add a setting for one theme-specific thing, there will be an expectation that other theme customisation should be in the UI. I just don’t have the resources to support that, and I prefer to encourage people to get involved and edit some code if they want to customise things beyond the basics.

**Comment by michaelwylde** [comment]
Yea that makes perfect sense, cheers!
