### ISSUE TITLE
Feature request - After editing a post return to http referer

### ISSUE THREAD

**Issue by thethinkingman** [xenocrat/chyrp-lite#128]
Hi,

I would like to have the Save button (in edit posts) to take you back to the http_referer instead of back to manage_posts.
This will provide the admin with an efficient means of editing posts.

After 'Saving' the post I am always sent back to "manage_posts". From there I have to click on Next to get to the page I was on, edit the next post, etc etc. Painful.

Also, if I edit a post from the Main page, click on Save.. it takes me to "manage_posts".

To test this out I have modified the following:

Added a referer item to the admin_edit_post() function in includes/controller/Admin.php: 
```
            $this->display("pages".DIR."edit_post",
                           array("post" => $post,
                                 "groups" => Group::find(array("order" => "id ASC")),
                                 "options" => $options,
                                 "feather" => Feathers::$instances[$post->feather],
                                 "referer" => $_SERVER["HTTP_REFERER"]));
```

Updated the admin_update_post() function in includes/controller/Admin.php:
After:
```
            if (isset($_POST['publish']))
                $_POST['status'] = "public";
```

I added:
`$referer = (isset($_POST['referer']) ? $_POST['referer'] : "manage_posts");`

Added the following line to admin/pages/edit_post.twig:
After:
`{% include "partials" ~ DIR ~ "post_fields.twig" %}`

I added:
`<input type="hidden" name="referer" value="{{ referer }}">`

I have tested this when editing from the main page as well as from manage_posts.

It seems to work and saves me a heap of time.

**Comment by xenocrat** [comment]
Hello there.

This is a nice quality of life feature, but `$_SERVER["HTTP_REFERER"]` is problematic because it is sent by the user agent and is not to be trusted. Luckily there is already a feature in Route class to keep track of the most recently visited URL on the site and store it in the user's session data. We can use it to send the user back to the place they were at before they visited the write/edit page.

I have an incoming commit that will reference this issue.

**Comment by thethinkingman** [comment]
Great. I think that it is nice to have.

I went through all of my posts and changed any links to the markdown equivalent. 
I then added a line of JS to add the target attribute to them -- so that the links open in a new tab.
