### ISSUE TITLE
Possible Feature Request - Cancel button on Edit forms

### ISSUE THREAD

**Issue by thethinkingman** [xenocrat/chyrp-lite#129]
On my website I have added a Cancel button to my post_fields.twig as I like the option to go back without saving.

I could click on the Back button (in the browser) but I find it to be intuitive to have a Cancel button.

Anyway, you can add it or not... but I like it and find it to be useful.

I have added these lines (at line 159) below the Save button in admin/partials/post_fields.twig

```
<button type="button" onclick="history.back()">
<img src="{{ site.chyrp_url }}/admin/images/icons/close.svg" alt="">{{ "Cancel" | translate }}
</button>
```

As can be seen, I am using Javascript to do the Back.. I could have used referer again (in the formaction attrbute on the button) BUT I don't like the idea of the form Posting data to the refering page.

Note: I have used the Close SVG instead of the Cancel SVG... as it looks better, and portrays the same message.

**Comment by xenocrat** [comment]
I prefer to let the browser's back button do the work here, but I'll leave this open. If it attracts votes I will revisit it.

**Comment by Torsten-K** [comment]
Not necessarily needed, but I like the idea, because not every user might be aware of the fact that simply clicking on the back button of the browser will do.
On the other hand, the Cancel button could be clicked accidentally. To avoid data loss, confirmation should be required.

**Comment by xenocrat** [comment]
This has been implemented in the latest release.
