### ISSUE TITLE
Help with RTL?

### ISSUE THREAD

**Issue by anas-almzoghy** [xenocrat/chyrp-lite#131]
Hi,

I'm working on an Arabic translation and wanted to shift the theme/layout to the right so it's more natural to the eyes. I've managed to do that for almost everything except the posts (title+content) both on the homepage and individual post page
![sc](https://i.postimg.cc/HsrfjfyP/image-2020-11-02-125048.png)

I think that it has to do with twig and not CSS, right? I've no experience with twig but can figure it out if pointed towards the right direction (file)

- Anas.

**Comment by xenocrat** [comment]
Hello there.

I don't have any experience here and so I had wrongly assumed RTL would happen automatically just by setting the HTML [`lang`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang) attribute to a RTL language, but I see now that's not the case. One way to set RTL manually is to use the HTML [`dir`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir) attribute on an element (this would be done in Twig) but the best way to transparently support it seems to be some extra CSS rules that check for a RTL language in the `lang` attribute. Some existing `text-align: left` rules also need to be overridden with the RTL-aware `start` keyword.

Today I've managed to get most things in Blossom and the admin console RTL with a few additional rules. I'll work on the other themes in the next few days. Look out for incoming commits that reference this issue. Thanks for raising this issue!

**Comment by anas-almzoghy** [comment]
Hi,

Sorry for my late reply. I've checked your edits and can conform that RTL is properly supported in both admin and blossom theme!
Here's the Arabic translation for the core Chyrp Lite. Themes, Feathers and Modules will follow soon. 
[ar_LY.zip](https://github.com/xenocrat/chyrp-lite/files/5501155/ar_LY.zip)

Sorry but I never could learn pull&push things in git :/

-- Anas

**Comment by xenocrat** [comment]
That's great news. Translation received with thanks! I've pushed it to the develop branch and credited you in the commit message.

**Comment by Alley041** [comment]
Persian in RTL too, i want to translate for you

**Comment by xenocrat** [comment]
Hello there,

All translations are gratefully received, thank you! You can make a pull request, or Zip the translation and attach it to a reply here. You can read more about creating and testing translations [on the wiki](https://github.com/xenocrat/chyrp-lite/wiki/Introduction-to-Translations).
