### ISSUE TITLE
[Feature Request] Latex (maybe mathjax?) support for showing mathematical formulae?

### ISSUE THREAD

**Issue by epsilon-0** [xenocrat/chyrp-lite#132]
This would be a nice addition to have for creating technical posts on our blogs.

Thanks!

**Comment by xenocrat** [comment]
Hello there.

Thank you for the feature request and the suggestion to use MathJax. I’m looking into it.

**Comment by epsilon-0** [comment]
Thank you so much!!

**Comment by xenocrat** [comment]
This has been implemented in the latest release.

**Comment by epsilon-0** [comment]
Thanks a lot!!!
I've upgraded it and its working awesomely :heart:
