### ISSUE TITLE
Guests can't access posts/pages with - "You are not allowed to view this site."

### ISSUE THREAD

**Issue by epsilon-0** [xenocrat/chyrp-lite#137]
For some reason the blog posts become hidden with the error message - "You are not allowed to view this site."

I am unsure what the mistake is with the permissions. I didn't consciously change any random settings.

**Comment by epsilon-0** [comment]
I just went back to `Admin > Settings > Users` and clicked `update` without changing anything, and it started working.

**Comment by xenocrat** [comment]
Thanks for the  report. I’ll attempt to reproduce it and discover the cause.

**Comment by epsilon-0** [comment]
I don't think this could be easily reproducible, the problem might have also happened because I was upgrading from a previous version.

**Comment by bart7782** [comment]
I just got this same issue and just clicking "update" fixed it too.

I reinstalled my site with a new webserver, everything was a fresh install exept for the database

**Comment by xenocrat** [comment]
Thanks for the report. Clearly this is a recurring problem so I'm reopening this issue and I'll try to get it resolved.

**Comment by xenocrat** [comment]
I've made some changes to the way the installer creates the permissions for each of the default groups. In my testing this reinstall bug has not occurred with these changes to the code, so hopefully it's fixed.
