### ISSUE TITLE
Custom theme not working

### ISSUE THREAD

**Issue by jocap** [xenocrat/chyrp-lite#143]
I copied the Sparrow theme to a new directory, edited info.php accordingly and tried to edit some files. None of the changes seem to apply. If I remove files, Chyrp Lite complains, but if I just remove all content inside them, the site displays normally, even though it should be broken. It's as though the Sparrow theme is still active.

Interestingly enough, the only file whose changes apply is stylesheets/all.css.

Any ideas?

**Comment by xenocrat** [comment]
Make sure to enable [debug mode](https://github.com/xenocrat/chyrp-lite/wiki/Debug-and-Tester-Modes). For a one time fix, delete the contents of _includes/caches/twig/_ to clear the Twig cache. In production mode, Twig template engine caches quite aggressively.

**Comment by jocap** [comment]
Thank you, I missed that.

28 feb 2021 kl. 23.21 skrev Daniel Pimley:
