### ISSUE TITLE
Themes and colors

### ISSUE THREAD

**Issue by viktor02** [xenocrat/chyrp-lite#144]
Hello. I want to create my own dark theme for chyrp, I have a question. 
Is the all.css file generated from something or is it written by hand? (Perhaps I did not find the sources of this file, if they exist, of course)
I would like to get something like variables for color as in less and other preprocessors, so as not to rewrite all the code by hand

**Comment by xenocrat** [comment]
Hello there. The CSS is all written by hand, without any preprocessor.

**Comment by viktor02** [comment]
Thanks for the answer
