### ISSUE TITLE
PHP 8 syntax error

### ISSUE THREAD

**Issue by EDx256** [xenocrat/chyrp-lite#145]
When trying to install chyrp on php8, a syntax error is presented

```
php -l /www/html/includes/helpers.php
PHP Parse error:  syntax error, unexpected token "match", expecting "(" in /www/html/includes/helpers.php on line 808
Errors parsing /www/html/includes/helpers.php
```

```
php --version
PHP 8.0.3 (cli) (built: Mar  5 2021 07:53:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies
```

Same issue in cli and fpm

If you paste contents of helpers.php into a php syntax checker, you get the same issue.
For example https://extendsclass.com/php-tester.html
Pick php 8, you get the error
Pick php 7, no syntax error

Probably caused by new php match expression
https://php.watch/versions/8.0/match-expression

**Comment by xenocrat** [comment]
Hello there.

I will investigate. Thank you for the report.

**Comment by xenocrat** [comment]
The problem should be fixed now in the develop branch.

**Comment by EDx256** [comment]
Installs and runs fine on php 8 for me
