### ISSUE TITLE
Docker Image?

### ISSUE THREAD

**Issue by shleeable** [xenocrat/chyrp-lite#146]
Hey, 

I'm shockingly happy to hear about the chyrp-lite fork. I loved chyrp.

Is there a docker image to maintain this environment easily?

**Comment by xenocrat** [comment]
Hello there and thank you for your interest!

I admit to having very little knowledge of Docker, so I speak mostly from ignorance here. I'm not sure there's much to gain from a Docker image of Chyrp Lite. I assume you'd already be using images for your web server and DBMS of choice, and for PHP. Beyond those requirements, Chyrp Lite is just some files copied to your web server's document path.
