### ISSUE TITLE
Ensure that JS is enabled during installation

### ISSUE THREAD

**Issue by kehugter** [xenocrat/chyrp-lite#15]
I didn't notice that Javascript was disabled during the installation, which lead to a strange behaviour and errors:
- selecting SQLite 3 as adapter didn't remove the MySQL fields
- some MySQL fields, like the table prefix, were getting passed to SQLite 3
- the site was created without any warning but there were dozens of "Database Error" messages at random intervals

Tested with the latest release and the develop branch.

A "you must enable Javascript" banner would solve the installation problem, but differentiating and validating SQLite and MySQL fields in the form would probably be a good idea.

**Comment by xenocrat** [comment]
Sorry that you did not have a good install experience. I see the cause of the problem and I've added some code to ensure only valid settings are configured for SQLite databases. Thanks for the report!

**Comment by kehugter** [comment]
No worries, you get used to an odd internet with NoScript :)
