### ISSUE TITLE
How can I translate the blog to portuguese?

### ISSUE THREAD

**Issue by alexandrediaries** [xenocrat/chyrp-lite#151]
Hi!

I have the Poedit installed, but I don't know where the files are located (to be translated).
 I would like to try to translate it to portuguese.

**Comment by xenocrat** [comment]
Hello there,

The files you need to get started translating are “.pot” template files. There’s an overview of how translations work in Chyrp Lite [here on the wiki](https://github.com/xenocrat/chyrp-lite/wiki/Introduction-to-Translations). In a nutshell, there are multiple .pot files for the different parts of the blog - you’ll find one in _includes/locale/en_US/LC_MESSAGES_ and the others inside the folders for each module, feather, and theme.

Let me know if I can help further!

**Comment by alexandrediaries** [comment]
> Hello there,
> 
> The files you need to get started translating are “.pot” template files. There’s an overview of how translations work in Chyrp Lite [here on the wiki](https://github.com/xenocrat/chyrp-lite/wiki/Introduction-to-Translations). In a nutshell, there are multiple .pot files for the different parts of the blog - you’ll find one in _includes/locale/en_US/LC_MESSAGES_ and the others inside the folders for each module, feather, and theme.
> 
> Let me know if I can help further!

Thank you very much for your answer. I will access the link you sent me.
👍
