### ISSUE TITLE
Feature request: Open graph tags

### ISSUE THREAD

**Issue by luxvw** [xenocrat/chyrp-lite#157]
[Open graph](https://ogp.me/) tags are used to generate rich preview card for links sharing on social media platforms like twitter, facebook and mastodon.

Basically I can get this done in a custom theme like

```html
<meta name="twitter:card" content="summary">
<meta property="og:title" content='{{ post.title | striptags | fix : "" }}'>
<meta property="og:url" content="{{ post.url() }}">
<meta property="og:site_name" content="{{ site.name | fix }}">
{% set desc = post.excerpt() | striptags | normalize | truncate(200) | fix(true) %}
<meta property="og:description" content="{{ desc }}">
<meta name="description" content="{{ desc }}">

{% if post.feather == "text" %}
  <meta property="og:type" content="article">
  <meta property="og:article:author" content="{{ post.author.name }}">
  {% if module_enabled("categorize") and post.category is defined %}
  <meta property="og:article:section" content="{{ post.category.name | oneof("[Untitled]") }}">
  {% endif %}
{% elseif post.feather == "photo" %}<meta property="og:image" content="{{ post.filename | uploaded }}"><meta property="og:type" content="article">
{% elseif post.feather == "video" %}<meta property="og:video" content="{{ post.filename | uploaded }}"><meta property="og:type" content="video">
{% elseif post.feather == "audio" %}<meta property="og:audio" content="{{ post.filename | uploaded }}"><meta property="og:type" content="audio">
{% elseif post.feather == "uploader" and post.image is defined %}
  <meta property="og:image" content="{{ post.image | uploaded }}">
{% endif %}
```

Then there is the `og:image`.

Since no "featured image" is defined in textual posts, the first image appeared in the post body would do the trick, like

```html
{% set image = post.excerpt() | preg_replace( '/^.*?<img [^>]*?src=[\'"](http.*?)[\'"].*?$/s',  '$1' ) | trim | fix %}
<meta property="og:image" content="{{ image }}">
```

Apparently the `preg_replace` filter isn't quite convenient here, maybe a module would do better? Or maybe an "image" field inserted into the text feather instead of some regex extraction?

I'm not familiar enough with php to know which would be the better performance. So I made this feature request.

**Comment by xenocrat** [comment]
Why not use the photo feather? The uploader feather also populates an “image” attribute if it discovers an image file among the uploads (see [here](https://github.com/xenocrat/chyrp-lite/blob/master/feathers/uploader/uploader.php#L186)).

**Comment by xenocrat** [comment]
Probably the best option here is to create a module that adds an optional post attribute. This can be done with a very simple module - take a look at how the [Rights module](https://github.com/xenocrat/chyrp-lite/blob/master/modules/rights/rights.php) defines the rights holder attribute.

Your code can then use the image URL entered in the option for each post, or a default image if empty (the `oneof` filter is useful for such cases).
