### ISSUE TITLE
`rows` attribute of `text_block` field

### ISSUE THREAD

**Issue by luxvw** [xenocrat/chyrp-lite#158]
The `text_block` field of quote feather was meant to be `"rows" => 5`, while `/admin/partials/post_fields.twig` has a hardcoded `rows="12"` for display.

**Comment by xenocrat** [comment]
The "rows" option hasn't been supported for some time. If it's absolutely necessary to override the default row height and other style choices, a feather can use [`respondTo`](https://github.com/xenocrat/chyrp-lite/wiki/Anatomy-of-a-Feather#this-respondto) and inject some CSS by responding to [admin_head](https://github.com/xenocrat/chyrp-lite/blob/master/tools/triggers_list.txt#L23).

I've removed the lines now. Thanks for spotting this!
