### ISSUE TITLE
Database error, comment `author_ip` numeric value out of range

### ISSUE THREAD

**Issue by luxvw** [xenocrat/chyrp-lite#159]
Failed to submit a comment because

> ERROR: Database error: SQLSTATE[22003]:   
> Numeric value out of range: 1264 Out of range value for column 'author_ip' at row 1   
> ...  
> Parameters Array ( .. [:author_ip] => 356980**** .. )

End up with changing the type of `author_ip` column to an unsigned int.

**Comment by xenocrat** [comment]
Thanks for the report. I think I see the problem. Is your PHP installation 64-bit?

**Comment by xenocrat** [comment]
This is now fixed in the develop branch. It was caused because PHP's `crc32()` function on 64-bit installations returns positive integers that are too big for the column. I've switched to an implementation of CRC-16 which will always fit in the column size.
