### ISSUE TITLE
Error in feed if no posts exist

### ISSUE THREAD

**Issue by kehugter** [xenocrat/chyrp-lite#16]
On a fresh install, `/?action=feed` returns

```
Error
Invalid argument supplied for foreach() (/var/www/chyrp/includes/controller/Main.php on line 751)
Backtrace

    includes/controller/Main.php on line 751
    includes/class/Route.php on line 122
    includes/class/Route.php on line 122
```

**Comment by xenocrat** [comment]
I've tracked down the cause of this error and I think I've fixed it (need to test a fresh install to be sure). Thanks for the report!

**Comment by kehugter** [comment]
Great! Thanks for the quick answer and chyrp-lite in general!

**Comment by kehugter** [comment]
Looking good here.
