### ISSUE TITLE
Weird error caused by disabling modules in debug mode

### ISSUE THREAD

**Issue by luxvw** [xenocrat/chyrp-lite#160]
In debug mode, disabling "Comments" or "Categorize" module cause error

> ERROR: Indirect modification of overloaded property Config::$routes has no effect

Then I go to site front page, it shows:

> ERROR: Requested configuration setting not found.

After exiting the debug mode  (i.e. deleting the "debug" file), things went normal again.

**Comment by xenocrat** [comment]
Thanks for the report. I assume you are using the develop branch. This is related to changes I’m making to ensure PHP 8.2 compatibility. I missed this issue but it’s easily fixed. Thanks!

**Comment by xenocrat** [comment]
This is now fixed in the develop branch. Once updated, disabling the modules again should fixed the errors encountered in DEBUG mode.
