### ISSUE TITLE
How do I list the child pages of the current page?

### ISSUE THREAD

**Issue by EzequielBruni** [xenocrat/chyrp-lite#162]
So yeah, just that. How would I list immediate child pages and pull in data like a bit of the content as an excerpt? I'm building a theme where the (optional static) home page is intended to display any immediate child pages in a list to allow things like listing projects, portfolio pieces, etc.

**Comment by xenocrat** [comment]
Hello there,

In Twig you would access this using `{{ page.children }}`. If there are no children, this will be an empty array. If there are children, you'll be able to iterate over them and create a 100 word excerpt using something like this:

    {% for child in page.children %}
    {{ child.body | striptags | truncate(100) }}
    {% endfor %}

Or you could just list the page titles:

    {% for child in page.children %}
    {{ child.title }}
    {% endfor %}

I hope that helps!

**Comment by EzequielBruni** [comment]
Thank you very much! It was a bit more complex in Typemill (which is also Twig-based), so I wanted to be sure.

**Comment by xenocrat** [comment]
I've listed a few notable extensions on the [wiki homepage](https://github.com/xenocrat/chyrp-lite/wiki) here and at [chyrplite.net](https://chyrplite.net/). I'd be happy to add your theme to the list. Looking forward to seeing it. :-)

**Comment by EzequielBruni** [comment]
Here it is: https://github.com/EzequielBruni/NewFolder-Blog-ChyrpLite/blob/main/README.md

It will probably need some refinement, and I'm not ready to assign the official "1.0" release thingy... but it's here. Now to do it all over again with HTMLy and Bludit because I'm an indecisive masochist.

**Comment by xenocrat** [comment]
Thanks for sharing!
