### ISSUE TITLE
Clean URLs in Preferences > Routes: Error (dev version)

### ISSUE THREAD

**Issue by Torsten-K** [xenocrat/chyrp-lite#164]
Recent development version: I changed to Clean URLs in Preferences > Routes, and now an error appears, when I switch to the manage tab:

_Error
urlencode(): Passing null to parameter #1 ($string) of type string is deprecated_

I removed the tick in the checkbox and now it works again. Seems like a bug to me.

**Comment by xenocrat** [comment]
I can't reproduce that error. Please can you create a file named "DEBUG" inside your includes folder. The file can be empty.

Then test again. Once Chyrp Lite is in DEBUG mode, you should see a backtrace from the error, which will help me pinpoint the issue.

**Comment by xenocrat** [comment]
Reproduced now. Fix is on the way. Sorry for that! :-)
