### ISSUE TITLE
FR: Post Views modul reset option

### ISSUE THREAD

**Issue by Tagirijus** [xenocrat/chyrp-lite#165]
Hey there,

first of all: thanks for this super lightweight blogging system. I like it already!

I activated the `Post Views` module to be able to see which posts are being viewed how many times. Unfortunately if you look at the draft as the author yourself, the view count will also increase.

It would be nice to have an option to reset the counter or so. Just an idea - no biggie after all. At the moment I use phpMyAdmin to clear the loggings directly in the DB.

Thanks for reading. Have a nice day / evening! (=

**Comment by xenocrat** [comment]
Hello there,

Thank you for the kind words. Those are good suggestions - I'll look into adding a reset option and definitely I will add some extra logic to the view counter so viewing your own post doesn't add to the count.

**Comment by Tagirijus** [comment]
Thanks for the feedback/reply and thanks for considering these features! (=

**Comment by Tagirijus** [comment]
I just try to understand how modules are being written _(already read the wiki!)_. In the meantime I thought that I made be able to help with translation as well, but unfortunately I have no real idea how I could do this the right way _(probably with a pull request or so!? Unfortuately I still do not 100% get how to do a pull request the right way, argh!)_. So I will just post the po-file here. Hopefully you don't mind:

```
msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: \n"
"PO-Revision-Date: \n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: de_DE\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: Poedit 3.0.1\n"

#. This file is distributed under the same license as the Chyrp Lite package.
#: modules/post_views/info.php:3
msgid "Post Views"
msgstr "Post Views"

#: modules/post_views/info.php:6
msgid "Counts the number of times your posts have been viewed."
msgstr "Zählt wie oft ein Post angeguckt wurde."

#: modules/post_views/info.php:10
msgid "Do you want to remove view counts from the database?"
msgstr "Möchtest du die View Zählungen aus der Datenbank löschen?"

#: modules/post_views/post_views.php:24
msgid "View Count"
msgstr "View Zahl"

#: modules/post_views/post_views.php:30
#, php-format
msgid "Download view count for &#8220;%s&#8221;"
msgstr "Lade View Zahlen für &#8220;%s&#8221; runter."

#: modules/post_views/post_views.php:47
msgid "An ID is required to download a view count."
msgstr "Es wird eine ID benötigt, um die View Zahlen runterzuladen."

#: modules/post_views/post_views.php:56
msgid "You do not have sufficient privileges to download this view count."
msgstr "Du hast nicht die nötigen Rechte, um die View Zahlen runterzuladen."
```

**Comment by xenocrat** [comment]
Thank you! I will add this to the repo.

**Comment by xenocrat** [comment]
Post View counter reset has been implemented in the latest release.

**Comment by Tagirijus** [comment]
Nice, thank you a lot! I am testing it out.
