### ISSUE TITLE
Is it possible to theme the administration area?

### ISSUE THREAD

**Issue by Tagirijus** [xenocrat/chyrp-lite#166]
Hey there,

I was wondering if it is somehow possible to theme or alter the admin area without hard-coding it into the files, which would probably be overwritten on an update?

For example: I would like to change the behaviour of the posts table. If I click on the title I'd like to get to the edit page and I would like to change the pen-icon to glasses or so and a click should view the post then _(so basically I want to switch these two links)_. I tried to add a `admin\manage_posts.twig` into my theme folder, but it seem not to overwrite the actual twig file. Am I doing something wrong or is this simly not possible via theming?

Would it be posible to solve this link-behaviour with a module?

Thanks for your help! (=

**Comment by xenocrat** [comment]
Hello there,

Unlike the main blog, the admin console can’t be customised with a theme. You could patch the file admin/pages/manage_posts.twig to swap the links around, or make a module to do the same with JavaScript.

I have no plans to support the kind of fine-grain customisation you need here, so I would recommend simply patching the file with your modified version. Yes, it will be overwritten when updating - but you can keep the modified version somewhere safe and overwrite it again after each update. That particular template file is quite stable now and unlikely to change much in future.

**Comment by Tagirijus** [comment]
Thanks for your reply. It's not a crucial thing to me. I mainly wanted to ask, if I had missed something in the theme system. The idea with the module+JS sounds interesting. Maybe I can find some time to look further into module writing etc. Thanks! (=

To not clutter the issues, I will close this one, since to me it is solved. (;
