### ISSUE TITLE
category and comment not appear

### ISSUE THREAD

**Issue by snydez** [xenocrat/chyrp-lite#167]
Hi, 
i just trying your chyrp 2021.04, and i found that category and comment not appeared.
i've turn on all from the extend.

please advise.
thanks

**Comment by xenocrat** [comment]
Hello there,

You need to give your group permission to manage categories after you enable the module. You can do this by visiting Admin > Manage > Groups, then edit the group your account belongs to and make sure the group has the newly added Manage Categories permission. Once that's done, you will find a new tab for Manage > Categories. Same procedure for comments. You also need to decide what groups of users are allowed to comment on posts.
