### ISSUE TITLE
Referer - AJAX error prevents installing extensions

### ISSUE THREAD

**Issue by kehugter** [xenocrat/chyrp-lite#17]
Trying to install any extensions results in an alert saying

> There was an error enabling the extension.

The POST seems to be wrong (missing values):

`action=enable_module&extension=highlighter&confirm=&hash=`

and returns the following HTML and response

> Access Denied: Invalid security key.

> Access Denied: Invalid security key.

Seems to be caused by blanked referers. If I disable AJAX or enable referers, extensions are installed normally. Fresh chyrp-lite install, latest release.

**Comment by xenocrat** [comment]
This is intended behaviour. A security key is required for some privileged ajax actions: toggle modules and feathers in the admin console, edit posts and comments inline on the blog. To guard against [cross-site request forgery](https://en.wikipedia.org/wiki/Cross-site_request_forgery), the security key is only added to the JavaScript file if the browser sends valid cookies and a referrer that matches the Chyrp URL when the file is requested.

If you are running with referrers disabled in your browser, you can switch off ajax features in Settings > Content and this will make the aforementioned functions fallback to form submissions and static pages.

**Comment by kehugter** [comment]
The reason of my report is that this is the first time I notice this extra security check in backend ajax request after testing a couple of dozen different CMSs this week.

Blanked referers, like #15, is something that will affect a very small percentage of users, so it isn't that important to lower the security if you consider referers an important check to do. Perhaps the alert message could be more descriptive.

**Comment by xenocrat** [comment]
Good idea, I will consider a better message for such occurrences.
