### ISSUE TITLE
Unable to view draft posts on website - regression?

### ISSUE THREAD

**Issue by nevadascout** [xenocrat/chyrp-lite#175]
I'm sure that I used to be able to view draft posts on my website by clicking their title from the post list in the admin area, but it doesn't work anymore. The link takes me to a 404 page on the website unless the post is published.

My work around for now is to change the status from "Draft" to "Admin", then I can at least view the post on the site before I make it public.

I'm sure this used to work, so this seems like a bug 🤔

**Comment by xenocrat** [comment]
Thanks for the report. Can you confirm your user group has the permissions “View Drafts” or “View Own Drafts”? I’ll check it out in the meantime.

**Comment by nevadascout** [comment]
I'm using the default Admin group, and it has both the "View Drafts" and "View Own Drafts" permissions.

**Comment by xenocrat** [comment]
Yes, I see the problem. It's due to an oversight when I was improving the efficiency of clean URL resolution for posts in the latest release. I've fixed this locally and tomorrow I will create a hotfix release to resolve both your reported issues. Thanks for letting me know!
