### ISSUE TITLE
Unable to view post preview in admin area

### ISSUE THREAD

**Issue by nevadascout** [xenocrat/chyrp-lite#176]
Clicking the eye icon from the edit toolbar above the textarea while writing a post shows me a dialog box with a PHP error inside:

<img width="933" alt="Screenshot 2022-12-22 at 18 30 08" src="https://user-images.githubusercontent.com/377089/209192391-813ca39b-59fe-434e-8038-3f21a09e51d4.png">

**Comment by xenocrat** [comment]
Hello there,

Thanks for the report. I assume you’re on PHP 8.2. Can your try patching the latest version of the file _includes/controller/Ajax.php_ from master?

**Comment by nevadascout** [comment]
I am using PHP 8.2 yes. Sorry should have included that in the original report!

Thanks, that version of `Ajax.php` from master has fixed the issue 👍
