### ISSUE TITLE
Having trouble setting up url rewrite support on Nginx (Solved)

### ISSUE THREAD

**Issue by bart7782** [xenocrat/chyrp-lite#179]
Hi there,

I had an issue but while i was writing it i fixed it. You may want to add this to your code or documentation. You problably have a better understanding of what i changed. 
I'm sorry for the weird format. If you have trouble understanding i can rewrite it if you want. I wrote it in the middle of troubleshooting.

Original issue:
I just tried to setup url rewrite support but i am having some trouble with it. 
In the log it states this: `nginx: [emerg] "location" directive is not allowed here in /config/www/include.conf:3`

Here i found how to fix the issue:
Online i found that a location directive should only be inside the server directive. So i tried adding it to /nginx/site-confs/default.conf instead and that fixed the issue.

My default.conf now looks like this: I added the code from include.conf and commented the old location code.
```
## Version 2022/10/04 - Changelog: https://github.com/linuxserver/docker-baseimage-alpine-nginx/commits/master/root/defaults/nginx/site-confs/default.conf.sample

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;

    server_name _;

    set $root /app/www/public;
    if (!-d /app/www/public) {
        set $root /config/www;
    }
    root $root;
    index index.html index.htm index.php;

    #location / {
        # enable for basic auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

    #    try_files $uri $uri/ /index.html /index.php$is_args$args =404;
    #}

    location ~ ^(.+\.php)(.*)$ {
        fastcgi_split_path_info ^(.+\.php)(.*)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include /etc/nginx/fastcgi_params;
    }

        location / {
            index index.php;
            rewrite \.twig$ /index.php;

            location  ^~ /admin/ {
                try_files $uri $uri/ /admin/index.php;
            }

    try_files $uri $uri/ /index.php;
}
```

My include.conf looked like this: (From when i tried it the offical way)

```
# Template to enable clean URLs for the nginx web server.

location / {
    index index.php;
    rewrite \.twig$ /index.php;

    location  ^~ /admin/ {
        try_files $uri $uri/ /admin/index.php;
    }

    try_files $uri $uri/ /index.php;
}
```

My nginx.conf looked like this: (From when i tried it the official way)

```
## Version 2022/08/16 - Changelog: https://github.com/linuxserver/docker-baseim>

### Based on alpine defaults
# https://git.alpinelinux.org/aports/tree/main/nginx/nginx.conf?h=3.15-stable

user abc;

# Support clean urls for chyrp-lite
include /config/www/include.conf;

... etc
```

**Comment by xenocrat** [comment]
I think the `include` would also work so long as it was inside the `server` directive. I will update the documentation and add a comment to _include.conf_. Thank you for the report and detailed resolution!
