### ISSUE TITLE
Only SQLite is available for installation

### ISSUE THREAD

**Issue by bart7782** [xenocrat/chyrp-lite#186]
Hi, I am currently trying to get chyrp running again because i lost my previous installation.

When installing i only have the option to install with an SQLite database. I would like to use a MySQL database instead. Is it checking the system for an installed version of MySQL? The server is running in a seperate docker container.

Also, am i doing this right? What would be the recomended way to reinstall Chyrp with an existing database with content in it already?

Thanks in advance,

**Comment by xenocrat** [comment]
Hello there,

You need to have the [PDO driver for MySQL](https://www.php.net/manual/en/pdo.installation.php) enabled.

It's fine to install using a database that already has a Chyrp Lite installation on it. Anything that already exists will be skipped during installation. Once installation completes, your previously created posts and pages should be visible.
