### ISSUE TITLE
FEATURE REQUEST: Demo Online via master domain name

### ISSUE THREAD

**Issue by ProfCyberNaught** [xenocrat/chyrp-lite#188]
I really think something like a PHP Blogging platform as this needs an online demo. This demo would display how the overall site looks, feels, and how the different themes look. Also, a demo back-end (could be refreshed/wiped every day or hourly via cron in the database), which displays how the GUI works, and allows people to interact with it.

I also feel you need plenty of screenshots for this platform to demonstrate quickly, how this looks from the front-end and the back-end.

Example URL could be demo.domainname.ext or a sub directory: domainname.ext/demo

**NOTICE:** _You do not have to let demo users publish data to the live demo site, but at least give them the opportunity to play around and experience the platform._

**ADDITIONAL:** _Please consider creating a Security Policy for this platform for controlling responsible reporting of any potential security issues or vulnerabilities._

[Security Policy Request](https://github.com/xenocrat/chyrp-lite/security/policy "Request/Suggest a Security Policy")

**Comment by xenocrat** [comment]
Thank you for your suggestions. I don't have the time to work on creating and securing a demo platform, but adding screenshots is certainly something I can work on. I'll add it to my to-do list.

A security policy has been created. ^_^

**Comment by ProfCyberNaught** [comment]
Thanks for getting back to me. I feel the security policy will certainly help with such a project like this. Also, the screenshots are essential to such a platform but fully understand the time constraints regarding setting up a dummy demo subdomain. This will take time to implement. I will certainly check back and look at the screenshots.

If you need assistance with this, please let me know and I can try help you out if you need an extra pair of hands.

Best wishes,
ProfCyberNaught

**Comment by xenocrat** [comment]
There are some screenshots on the project homepage now. It's a basic implementation, but I think it works to show people some of what Chyrp Lite has to offer. I'll continue to consider this topic in future, and possibly do something more elaborate at some point. Thank you again for the suggestion!

**Comment by ProfCyberNaught** [comment]
Thanks for the update and taking the time to add the screenshots. It certainly helps to assist those coming to the website and seeing how this project looks, and the simplistic nature of the platform as intended. I can also see you added link text and ALT text which is great to see. So many debates I have because people keep leaving this out. Looks much better so thank you for implementing this. Will be good to see a demo instance when you eventually get the time. :+1:
