### ISSUE TITLE
Changing the favicon

### ISSUE THREAD

**Issue by bart7782** [xenocrat/chyrp-lite#190]
Hi again,

How can i change the favicon of the website? I tried replacing favicon.ico in the root but that did not seem to make a difference.

I have enabled Development mode, both on Chyrp and on Cloudflare.
I have tried accessing my site from a guest window and from another device.

Thanks,
Bart

**Comment by xenocrat** [comment]
Replacing favicon.ico and favicon.svg will do it. However be aware that browsers tend to cache favicons very aggressively; some never check for updates once the favicon is fetched and cached locally. You might also need to clear your browser caches completely to see changes take effect.

**Comment by bart7782** [comment]
I was not aware of the favicon.svg. I will try again later and also replace the favicon.svg.

**Comment by bart7782** [comment]
Sorry for the late reply but i managed to update the favicon. Just replace the ico and svg and wait patiently
