### ISSUE TITLE
Minimum PHP version requirement missing in README 

### ISSUE THREAD

**Issue by kmzby** [xenocrat/chyrp-lite#191]
Well, subj

**Comment by xenocrat** [comment]
Hello there,

I thought the link to https://www.php.net/supported-versions.php made it self-evident. Perhaps not. ;-)

**Comment by kmzby** [comment]
Thanks!

The rationale behind this issue was that:
1) there might be lots of people who has no idea which php versions are supported by upstream and just wanna use the product;
2) some major distros, i.e. RHEL/CentOS 7/8, Debian stable which are still supported don't provide php8 out-of-the-box

**Comment by xenocrat** [comment]
Fair enough. I’ve made it clear in the readme now. Thanks for raising the issue!
