### ISSUE TITLE
Feature request: keep the title and content when switching between tabs when writing a blog 

### ISSUE THREAD

**Issue by shukebeta** [xenocrat/chyrp-lite#192]
I mean switching between Text/Photo/Quote/Link/Uploader. Sometimes I have written quite a lot before I found I am in the wrong tab.  Currently, I have to manually backup the content somewhere, which is not convenient.

It would be much convenient if chyrp has this feature.

**Comment by xenocrat** [comment]
Thanks for the suggestion. I will have a think about how this could be done.

**Comment by xenocrat** [comment]
I’ve implemented this feature in the develop branch. It will be included in the next release.
