### ISSUE TITLE
Caching issues

### ISSUE THREAD

**Issue by xdpirate** [xenocrat/chyrp-lite#207]
Whenever a post is edited, the cache has to be cleared (ctrl+refresh) to reflect the changes. I've seen this behaviour in the post editor and on blog post pages. This seems to have gotten better since the last update, but I can still trigger the caching issue in the Manage > Uploads page, where if I delete an upload, it will still be in the list until I force refresh the page.

**Comment by xenocrat** [comment]
Hello there,

I assume you are using the Cacher module. I'm glad it's gotten better with recent updates and I think I see the issue causing continued problems when deleting files in Manage > Uploads. I'll aim to have this fixed in the next release.
