### ISSUE TITLE
no comments or likes 

### ISSUE THREAD

**Issue by roughnecks** [xenocrat/chyrp-lite#209]
Hello,

I just installed chyrp-lite and enabled a few modules, like comments and likes.

With the dark theme it doesn't show anything while with e.g. the blossom theme I see the text "0 comments" but there's no way to add one.. like no controls, no form.

What am I doing wrong?
Thanks

**Comment by xenocrat** [comment]
Hello there,

You need to enable commenting and liking permissions for the groups of users you want to have those abilities. See issue #62 and [this wiki page](https://github.com/xenocrat/chyrp-lite/issues/62).

**Comment by roughnecks** [comment]
> Hello there,
> 
> You need to enable commenting and liking permissions for the groups of users you want to have those abilities. See issue #62 and [this wiki page](https://github.com/xenocrat/chyrp-lite/issues/62).

Thank you, fixed!!

**Comment by roughnecks** [comment]
Sorry to reopen this but the Umbra theme is still missing the "comments" link at the bottom of each post..

**Comment by xenocrat** [comment]
Umbra doesn't implement the comment count as part of the post metadata. All the themes have slight differences in what features I supported and how I chose to implement them. This is intended to showcase a range of theming possibilities and give each theme a unique flavour beyond just styling.

If you'd like to add comment count to Umbra's post metadata, compare Sparrow's template file _[post.twig](https://github.com/xenocrat/chyrp-lite/blob/master/themes/sparrow/content/post.twig#L41-L50)_ to Umbra's _[post.twig](https://github.com/xenocrat/chyrp-lite/blob/master/themes/umbra/content/post.twig)_ and you'll see how to easily add that functionality.

**Comment by roughnecks** [comment]
Thanks, much appreciated.
