### ISSUE TITLE
No menu when browsing from mobile

### ISSUE THREAD

**Issue by roughnecks** [xenocrat/chyrp-lite#210]
Hello,

I had been tinkering a bit with my blog and I'm not sure when this happened.
From my mobile phone I used to have a "menu" button at the bottom of the screen, but now it's vanished.. I tried topaz and blossom themes, same behavior, so now I can't login, view public pages etc.. only the blog posts are accessible.

Is it something I messed up? Thanks

**Comment by roughnecks** [comment]
I found the problem.

In a post of mine have some lines of `code` which exceeds the width of the page and the footer with menu button is extended far to the right, until the end of the page scrolled.. The actual menu button is hidden in the middle of this very long footer.

Hope that makes sense

**Comment by roughnecks** [comment]
![image](https://github.com/xenocrat/chyrp-lite/assets/1666536/b1176255-e41a-46f6-9df6-0551f1567f76)

**Comment by xenocrat** [comment]
Hello there,

Thank you for sharing the cause of the issue. The mobile menu for Blossom and Topaz will be changing to something simpler in the next release, which should take care of this problem as well.
