### ISSUE TITLE
404 errors on nginx after a few silly changes

### ISSUE THREAD

**Issue by supersophie** [xenocrat/chyrp-lite#212]
Hi,

I installed the latest release.  Worked well until I set the Clean URLs option, and the it spat out errors. I remember a similar problem with the original Chyrp when I set CleanURLs when running on apache. But now I have a similar problem with Nginx many years later. 

Alternativly, it could be that I copied the blosson theme to new theme, and change the background-color in one of the ul-background settings in the all.css file themes/blossompink/stylesheets/all.css I have it selected as a theme.  

1. Which tables must I update to remove Clean URLs.
2. Which table must I updated to put it back to Blossom?

**Comment by supersophie** [comment]
e.g http://www.example.org/admin/settings/

2023/10/11 21:54:31 [error] 353940#353940: *5215 "/var/www/www.example.org/admin/settings/index.php" is not found (2: No such file or directory), client: 21.2.2.5, server: www.example.org, request: "GET /admin/settings/ HTTP/1.1", host: "www.example.org"

**Comment by xenocrat** [comment]
All themes support clean URLs. Clean URLs are a configuration setting stored in _includes/config.json.php_ as a boolean (`true` or `false`).

For nginx additional steps are required after switching on clean URLs in the admin console: see [this wiki page](https://github.com/xenocrat/chyrp-lite/wiki/Supporting-Clean-URLs).

**Comment by roughnecks** [comment]
Not going to open another issue, since I have a similar problem with Clean URLs

```
server {
    #...
    include filesystem/path/to/chyrp/include.conf;
    #...
}
```

This is the snippet for nginx but I cannot find any "include.conf" file in the tarball..

**Comment by supersophie** [comment]
Agreed.  Me neither:

```
# find . -name include.conf
#

```

**Comment by supersophie** [comment]
And you are right.  I just enabled Clean URLs, chyrp served a 404, and lo and behold the conf was created :-)

# find . -name include.conf
./include.conf
#

**Comment by roughnecks** [comment]
I added that include line and it's fixed, had to remove this bit:

```
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
```

but the index I haven't touched.

**Comment by supersophie** [comment]
I don't think we have to, but my additional location / got in the way.

I removed the include statement, and did this for mine:

```
        location  / {
                limit_req   zone=app burst=5;
                limit_rate 64k;
                allow  all;

        index index.php;
        rewrite \.twig$ /index.php;

        location  ^~ /admin/ {
                try_files $uri $uri/ /admin/index.php;
        }

                try_files $uri $uri/ /index.php;

        }

```

Seems to work :)
