### ISSUE TITLE
Can I edit a .twig file for a theme?

### ISSUE THREAD

**Issue by roughnecks** [xenocrat/chyrp-lite#215]
Hello,

I was trying to remove the "Blog" link from my site's sidebar, so I edited `themes/topaz/content/sidebar.twig` and removed these lines:

```
<li>
<a href="{{ url('index') }}">{{ "Blog" | translate }}</a>
</li>
```

but nothing really changed. Is that correct? Do I need to perform additional steps to modify a theme?

Thanks

**Comment by xenocrat** [comment]
Delete the contents of _includes/caches/twig_ or enable [debug mode](https://github.com/xenocrat/chyrp-lite/wiki/Debug-and-Tester-Modes).

**Comment by roughnecks** [comment]
> Delete the contents of _includes/caches/twig_

Perfect, worked like a charm. TY
