### ISSUE TITLE
Keep the left sidebar in place while scrolling down the blog

### ISSUE THREAD

**Issue by roughnecks** [xenocrat/chyrp-lite#218]
Hello,

pretty much "title", can we have an option to keep the sidebar menu stuck in place while scrolling the blog?

Thanks

**Comment by xenocrat** [comment]
Hello there,

You can do this with a minor modification to the CSS. Switch to `position: fixed;` in [this rule](https://github.com/xenocrat/chyrp-lite/blob/master/themes/blossom/stylesheets/all.css#L507-L513). But beware that I don't do this for a good reason: if the sidebar is taller than the screen height, there will be no way for the visitor to scroll down and make the lower part visible.

**Comment by roughnecks** [comment]
I think you're right, but can you tell how many months of Archive are shown in the sidebar? I'm using topaz theme.

**Comment by xenocrat** [comment]
The call to [`theme.archives_list()`](https://github.com/xenocrat/chyrp-lite/blob/master/themes/blossom/content/sidebar.twig#L92) accepts a number of months as an argument; default is 12.

**Comment by roughnecks** [comment]
ok, I decided to go rough and removed blog/email/archive from the sidebar and menu, then fixed the sidebar itself.
Will see out it goes :)

Thanks for the tips.
