### ISSUE TITLE
Ko-Fi button/widget (JS)

### ISSUE THREAD

**Issue by roughnecks** [xenocrat/chyrp-lite#219]
Hi there,

is there a way to add Ko-Fi to the blog?

Thank you.

**Comment by roughnecks** [comment]
OK, I just tried and added it to my theme's layout and it worked.. If there's a better way please let me know.

**Comment by xenocrat** [comment]
Hello there,

If you are maintaining your own theme, this is a perfectly reasonable way to do it. You could also do it by [creating a simple module](https://github.com/xenocrat/chyrp-lite/wiki/Making-Your-First-Module) to inject content in response to the `javascript` and `end_content` triggers, which would allow you to maintain the Ko-Fi button integration separate from the theme and enable/disable it easily from the admin console.

There is no right or wrong way, so if you have it working and you are happy, then all is well.
