### ISSUE TITLE
switch to git from release

### ISSUE THREAD

**Issue by roughnecks** [xenocrat/chyrp-lite#222]
Hello, me again :)

Is it possible to switch to git from release version if I have already configured the blog? (no content is in yet)
I have a sqlite database, so that should not be an issue but, there are files inside the blog directory I need to keep? I also set up the route already.

Thanks

**Comment by xenocrat** [comment]
Hello there,

You mean to upgrade from the current release version to the latest available on GitHub? Yes, you can follow the [normal upgrade procedure](https://github.com/xenocrat/chyrp-lite/wiki/Getting-Started#upgrading). Be aware that _downgrading_ is not guaranteed to be possible, although in most cases it should be fine.

The master branch on GitHub should usually be fairly functional - I try not to have it be broken - but be aware that only tagged releases have undergone my full (and fully inadequate 😉) pre-release testing process.

**Comment by roughnecks** [comment]
Okay, but how do I clone from git? I have to delete all files in my /blog directory first, right? (keeping /uploads and includes/config.json.php)

**Comment by xenocrat** [comment]
To be honest, I'm not very experienced with git beyond what I've learned to work on my projects. But I can tell you that when you are tinkering with Chyrp Lite, the important things to not delete are:

1. Your database (this is most relevant if using SQLite, although it should be stored outside web document root and therefore not an issue)
2. _/includes/config.json.php_
3. _/uploads_
4. If using Clean URLs: _.htaccess_, _include.conf_, and _caddyfile_.

These items are the ones that hold important configuration and data related to your blog - everything else can be erased/overwritten. I hope that helps!

**Comment by roughnecks** [comment]
Thanks
