### ISSUE TITLE
Change sender email address domain

### ISSUE THREAD

**Issue by roughnecks** [xenocrat/chyrp-lite#223]
Hi,

my blog is sending registration emails from www-data@domain.space, which is the actual domain.
Recently I discovered that the space domain gets rejected by some known providers like Gmail, so I bought and set up an .eu virtual domain on postfix.

Since there's no email settings in chyrp-lite, is there any way I can configure it to send mail from www-data@domain.eu?

Thanks

**Comment by roughnecks** [comment]
Ok, think I got this by rewriting address in postfix.
Will leave this open if you have suggestions, otherwise feel free to close.

**Comment by xenocrat** [comment]
Chyrp Lite uses PHP's [`mail`](https://www.php.net/manual/en/function.mail) function, with the From field set using the site contact email configured in settings. You can change that email address, use a module to respond to the "send_mail" trigger, or do it in the MTA as you have done.

**Comment by roughnecks** [comment]
Hi there.

I don't want to reopen this report, but to add a related question.
How am I supposed to cope with site's email address being from a domain which I don't administer?

I'm getting these logs when someone registers:

```
postfix/pickup 103BD92118C: uid=33 from=<www-data>
postfix/cleanup 103BD92118C: message-id=<20260111114839.103BD92118C@>
opendkim 103BD92118C: no signing table match for 'admin@domain_I_dont_administer.net'
opendkim 103BD92118C: no signature data
```

The `domain_I_dont_administer.net` is managed by friends and that email address is served by an external provider (I don't even know the details). So our chyrp uses `domain_I_dont_administer.net` and the contact email is `admin@domain_I_dont_administer.net`

The (also mail) server which actually runs chyrp, serves another mail domain.
It's just about that DKIM issue, because emails get delivered, but they may be blocked or sent to spam, eventually.

Thanks
