### ISSUE TITLE
Menu button on mobile disappeared

### ISSUE THREAD

**Issue by roughnecks** [xenocrat/chyrp-lite#227]
Hello,
I upgraded my blog to Varied and I just realized that on mobile there is no menu button anymore on the bottom of the screen.

I'm using a Xiaomi Redmi 6A, old phone.

**Comment by xenocrat** [comment]
The menu button has moved to the top of the page, below the search box. It can now be used to toggle the full site menu on/off, it no longer requires JavaScript, and makes the blog more friendly to assistive technologies and SEO.

**Comment by roughnecks** [comment]
Can't see anything in the topaz theme ¯\_(ツ)_/¯ Only my posts

**Comment by xenocrat** [comment]
Please clear your browser cache and try again.

**Comment by roughnecks** [comment]
Ooh, right! Thought refreshing the page would be enough 👍
