### ISSUE TITLE
Embedding owncast video

### ISSUE THREAD

**Issue by roughnecks** [xenocrat/chyrp-lite#229]
Hi,

I tried embedding an owncast video in a page with "Easy Embed" extension, using the link `http://your.host/embed/video`, but it's not working.

I followed here: https://owncast.online/docs/embed/?source=admin

Any way I can add that, even by using html?

Thanks

**Comment by roughnecks** [comment]
Not sure if I should see the video interface when not actually streaming, in that case I will check later on.

**Comment by xenocrat** [comment]
Hello there,

Easy Embed is able to support a few well-known services that use the same content ID for their direct links and embeds, by translating, for example, `youtube.com/watch?v=[video ID]` into `www.youtube.com/embed/[video ID]`. Easy Embed currently supports YouTube, Vimeo, Twitch, and Archive.org.

For Owncast, you would use the code snippet on that documentation page:

````
<iframe
  src="https://your.host/embed/video"
  title="Owncast"
  height="350px" width="550px"
  referrerpolicy="origin"
  allowfullscreen>
</iframe>
````

**Comment by roughnecks** [comment]
OK, but how I do I use that code in a page?

**Comment by roughnecks** [comment]
I added <html> and <body> tags and now it shows, if that's the right way..

**Comment by roughnecks** [comment]
Also thanks :)
