### ISSUE TITLE
Enhancement: Admin textarea monospace font

### ISSUE THREAD

**Issue by mord0d** [xenocrat/chyrp-lite#231]
IMO, It would be better to use monospaced font for textarea in admin panel:

- Better Markdown readability;
- Better HTML readability (Markdown don't support complex things[^1]);
- Better code readability (for those who write code in their blog).

[^1]: Markdown is broken inside HTML tags (e.g., `<span>sometext[^1]</span>` ← footnote tag will be shown as is), but it's not an issue.

---

The hard way: Ability to switch to old behavior.

A new variable like `site.admin_textarea_font_monospace` can be added, styles for textarea generated from twigs (`*_edit`, `*_write`):

```
<styles>
  textarea.body_field {
    font-family: {% if site.admin_textarea_font_monospace %}"Cousine Regular", monospace
      {% else %}"Open Sans Regular" sans-serif
      {% endif %};
  }
</styles>
```

*// If I understand Twig corrent, this should work.*

**Comment by xenocrat** [comment]
Thank you for the suggestion. I'll give some thought to implementing this, and I'll look into the footnote bug.

**Comment by mord0d** [comment]
>I'll look into the footnote bug

I found this bug when I tried to add a footnote inside html table, then I tested with code backticks and so on, Markdown doesn't work inside a html code at all:

```
<table>
<thead>
<tr><th>1</th><th colspan=2>2</th></tr>
</thead>
<tbody>
<tr><th rowspan=2>3</th><td colspan=2>~~4~~</td></tr>
<tr><td colspan=2>
5[^1]
</td></tr>
<tr><td>**one**</td><td>`two`</td><td>*three*</td></tr>
</tbody
</table>

[^1]: test footnote
```

**Comment by xenocrat** [comment]
This is correct behaviour according to the [CommonMark spec](https://spec.commonmark.org/0.30/#html-blocks).

**Comment by mord0d** [comment]
> This is correct behaviour

So, as I said earlier, it's not an issue. ☺

> according to the CommonMark spec

Thanks for the link.

**Comment by xenocrat** [comment]
Monospace font option will be in the next release. Thanks for the suggestion!
