### ISSUE TITLE
any user management for chyrp?

### ISSUE THREAD

**Issue by fgroupindonesia** [xenocrat/chyrp-lite#233]
i just wondering if chyrp could be implementing the same features as user management for different content given.
I remember about the user category that helps the content to be visible for certain users categories only.

is it possible? how?

**Comment by xenocrat** [comment]
Hello there,

Chyrp Lite provides a lot of control for choosing what different groups of users can see and do on your blog. Blog posts can also be made available only to specific groups of users. Can you explain what it is you want to do?
