### ISSUE TITLE
ko-fi script shows when opening menu in mobile browser

### ISSUE THREAD

**Issue by roughnecks** [xenocrat/chyrp-lite#234]
Hello,

I'm running chyrp-lite with the topaz theme. I added a script for ko-fi widget at the bottom of the sidebar code, just before the end `</div>`.

Now I noticed that when I open the blog's menu on mobile, the script shows up under "Archive", see image.

![image](https://github.com/xenocrat/chyrp-lite/assets/1666536/38c6805b-a1be-4eb2-a58a-a05cb341fbf1)

I think I'm doing this wrong or is there a setting to make the menu not to parse some code in the sidebar.twig?

Thanks!

**Comment by xenocrat** [comment]
Can you share a link to the site? I'll inspect the source and tell you what's going wrong.

**Comment by roughnecks** [comment]
> Can you share a link to the site? I'll inspect the source and tell you what's going wrong.

sure! https://blog.woodpeckersnest.space/

**Comment by roughnecks** [comment]
Thanks! Fixed.
