### ISSUE TITLE
Posts author

### ISSUE THREAD

**Issue by doesnmisclown** [xenocrat/chyrp-lite#235]
Hello i don't find how to define post author
in comments we can use `comment.author_link` but what is used for posts?

**Comment by xenocrat** [comment]
Hello there,

You can access an object containing useful information about the author of a post using the [`author()` method](https://github.com/xenocrat/chyrp-lite/blob/master/includes/model/Post.php#L1065): `$post->author()` in PHP and `post.author` in Twig. For example, you can get the author's name in Twig using `post.author.name` and the author's website by using `post.author.website`.

If you need to access the complete user object for the user who created a post, you can use `$post->user` in PHP, or `post.user` in Twig. Then you can access all the properties of that user: for example, `$post->user->group_id`. You could even grab all the posts created by the user who created this post by using `$post->user->posts`.

I hope that helps!
