### ISSUE TITLE
iframe height

### ISSUE THREAD

**Issue by roughnecks** [xenocrat/chyrp-lite#237]
Hello.

I have an iframe inside a page: https://blog.woodpeckersnest.space/services/health-status/
height isn't respected anymore, used to work before upgrading to sombre..

**Comment by xenocrat** [comment]
Hello there,

Remove `height: auto` from the iframe rule:

````
iframe {
    width: 100%;
    /*! height: auto; */
    border: none;
    margin: 1rem 0rem;
}
````

I'll remove this CSS property from all themes for the next release, since it annoyingly overrides `height` attributes in the `<iframe>`.
