### ISSUE TITLE
Feature Request - Support for icon libraries

### ISSUE THREAD

**Issue by MaggiWuerze** [xenocrat/chyrp-lite#241]
Would it be possible to add support for icon libraries like Font-Awesome or Glyphicon?
Or is there already something like this?

**Comment by xenocrat** [comment]
Hello there,

No plans to add this to the core, but it should be quite easy to bundle with a module or theme if needed. What is your use case?

**Comment by MaggiWuerze** [comment]
Basically I want to use chyrp as my website for documentation and wanted to put links to like the corresponding github or docker repo. Next to those I wanted to put the respective icon, but with the usual image tag they are to large and not affected by font size.

I would also use them inside the documentation like a yellow warn triangle or similar. Some of that is doable with emojis, but Font-Awesome (for example) has support for stuff like rotating and combining icons

**Comment by MaggiWuerze** [comment]
Oh nice, I will try that. Thanks for the help

**Comment by MaggiWuerze** [comment]
Do I need to do anything after changing the default.twig? None of the changes I make are reflected on the page

**Comment by MaggiWuerze** [comment]
Are the themes cached in chyrp? Edits I make only seem to take effect when I copy them into a "new" theme with a different name. Restarting doesnt help

**Comment by xenocrat** [comment]
Yes, the Twig template engine caches quite aggressively. You can disable this for theme development by enabling [debug mode](https://github.com/xenocrat/chyrp-lite/wiki/Debug-and-Tester-Modes).

**Comment by MaggiWuerze** [comment]
This works for me. Maybe I'll do a PR for a module later. Thanks for the help.
