### ISSUE TITLE
Cannot activate account

### ISSUE THREAD

**Issue by roughnecks** [xenocrat/chyrp-lite#243]
Hello,
a new user wanted to register on my blog but after clicking on the confirmation email and trying to login, this message appears:  "Si deve attivare un tuo account prima di poter accedere."

I tried registering myself with a secondary email and that happened to me too.
Moreover I cannot manually activate those accounts from the control panel, even if it says "Utente aggiornato." When I click on the "activate" checkbox, another email is sent to my address with the same activation link.

Can you help? Thanks

**Comment by xenocrat** [comment]
Hello there,

Thank you for the report. This does indeed seem to be a bug. I think I've fixed it in the branch [2024.01](https://github.com/xenocrat/chyrp-lite/tree/2024.01) with this commit: [Core: fixed bad SQL_DATETIME_ZERO_VARIANTS tests](https://github.com/xenocrat/chyrp-lite/commit/3a6bf104db3665bc1df7ea27be97eb3965644b72) - please can you patch and confirm?

**Comment by roughnecks** [comment]
What's the best way to patch? I'm running the latest tarball.
I mean, I could do that manually but if there's a smoother way..

**Comment by roughnecks** [comment]
I patched manually on my personal blog and activated successfully with the mail link I got previously.

**Comment by xenocrat** [comment]
That's great, thank you. I'll prepare a release with the fix.

**Comment by roughnecks** [comment]
Can I patch everything manually even after the release? Would like not to have to redo all of my changes to theme and css.

**Comment by xenocrat** [comment]
You can do, but for major releases there will be many changed files and the process will be quite laborious. For a hotfix release just a few files will change. The best way to handle your situation is to copy your theme somewhere safe during the upgrade and then put it back in place afterwards. If you modify a built-in theme, I recommend renaming it (by renaming the folder and the displayed name in _info.php_) so it doesn't clash with built-in themes when you upgrade, and therefore you don't risk having it overwritten.

**Comment by roughnecks** [comment]
OK, when you'll release the major one I'll obviously do it the proper way.
But if I rename my theme, how can I know if there were changes in a release for the theme too?

**Comment by xenocrat** [comment]
The simplest way is to take a look at the [commit history](https://github.com/xenocrat/chyrp-lite/commits/master/themes/topaz) for the theme.

**Comment by roughnecks** [comment]
Okay.
One last thing: I copied the umbra theme into another directory and changed its name in info.php but when I activate it as default theme, all of the menu items on top become English instead of Italian (Admin, Archive, logout etc..). Any way to fix that?

**Comment by xenocrat** [comment]
Sorry, I forgot about that. Yes, you need to change the [translation file names](https://github.com/xenocrat/chyrp-lite/tree/master/themes/umbra/locale/it_IT/LC_MESSAGES)  to match your new name for the theme folder.

**Comment by roughnecks** [comment]
I renamed those files for the IT language but it didn't work. I also removed all the twig cache files and refreshed page.

**Comment by xenocrat** [comment]
Works here. To be clear, you have to do the following:

1. Duplicate the _themes/umbra_ directory and rename it e.g. "umbra\_custom".
2. Rename the file _themes/umbra\_custom/locale/it\_IT/LC\_MESSAGES/umbra.mo_ to "umbra\_custom.mo"

**Comment by roughnecks** [comment]
That's what I did:

```
/var/www/xmpp-it/themes/xmpp-it/locale/it_IT/LC_MESSAGES# ls
xmpp-it.mo  xmpp-it.po
```

**Comment by xenocrat** [comment]
That looks right. Could be there is a permissions problem with the directory hierarchy or the file that is preventing Chyrp Lite from reading it.

**Comment by roughnecks** [comment]
You're right, I changed ownership to www-data and it's working now. Thanks again, I'm closing this.
