### ISSUE TITLE
I cannot see the "likes" column in manage posts

### ISSUE THREAD

**Issue by roughnecks** [xenocrat/chyrp-lite#244]
Hello again :)

These are 2 screenshots, one from me (first user of the blog) and one from another admin. In my shot the "likes" column is missing.

![55551846-f32d-472d-8d2c-e3bec73ed665](https://github.com/xenocrat/chyrp-lite/assets/1666536/bdb24f8e-8d9b-45df-a7c3-271eaa0661fd)

![e2eea6de-2d6b-4ee7-888b-f4bf3f686229](https://github.com/xenocrat/chyrp-lite/assets/1666536/25d291a5-f631-4c09-a2d6-b0bd492ea2c6)

**Comment by xenocrat** [comment]
That's very strange. Can you inspect the page source (or dev tools) and confirm the column is not present for you? The logic that renders that table column is very simple and there shouldn't be any way for it to not be rendered.

**Comment by roughnecks** [comment]
Just found out it was uBlock Origin to block that. I really don't know why or what list is causing that.

Thanks
