### ISSUE TITLE
nonstandard spacing around equals sign in chyrplite.net home page

### ISSUE THREAD

**Issue by timoteostewart** [xenocrat/chyrp-lite#245]
On the home page for https://chyrplite.net/ in one of your meta tags there are spaces around the equals sign. It's not standard, and since it's not a particularly important attribute (just the viewport), it might not matter whether visitors' web browsers correctly interpret it or not. But as a courtesy, I thought I would let you know in case you decide to fix it! Here's the entire `<head>` section of your web page:

```
<head>
  <meta charset="UTF-8">
  <title>Chyrp Lite</title>
  <meta name="author" content="Daniel Pimley">
  <meta name="description" content="Chyrp Lite is an ultra-lightweight blogging engine, written in PHP.">
  <meta name="viewport" content="initial-scale = 1.0">
  <link rel="icon" sizes="32x32" type="image/x-icon" href="favicon.ico">
  <link rel="icon" sizes="any" type="image/svg+xml" href="favicon.svg">
  <link rel="mask-icon" href="favicon.svg" color="#4f4f4f">
  <link rel="alternate" href="rss/update.xml" type="application/rss+xml" title="Chyrp Lite Releases">
  <link rel="stylesheet" type="text/css" href="css/chyrplite.css">
</head>
```
And the specific `meta` tag that has nonstandard spacing around the equals sign is this one here:

```
  <meta name="viewport" content="initial-scale = 1.0">
```

Good luck with your Chyrp Lite project! It looks fascinating. 

Best,
Tim

**Comment by xenocrat** [comment]
That's a fun project, thanks for sharing!
