### ISSUE TITLE
Chyrp is Too Wide for my Screen Display

### ISSUE THREAD

**Issue by thatgrrl** [xenocrat/chyrp-lite#249]
I have low vision so my desktop display is set at 125%. This does cause display issues with some websites. I'm often zooming out again so items on sites aren't hiding each other. Those are usually the sites which were not too small anyway. I need the bigger screen size for sites which use small print, and even more for those with low contrast between the background colour and their text, plus a tiny font.

Anyway, just posting that for others who wander in and read here, not knowing the general issue. 

Chyrp does have a good screen size and contrast. That was the first thing I noticed! I have no trouble reading the wiki etc. But, because my screen is set larger, Chyrp itself is wider than my screen. This means the right edge is out of sight. 

I mainly noticed it when typing a post. I touch type so I just go on typing knowing its there even if I can't see the whole thing. So I was going to ignore the issue as a small thing. But, when I set the categories up to show in Admin/Group (as you wrote to solve another issue here earlier) I could not see the buttons to edit settings for the Group. They were off to the right, just out of the screen. It took me a few minutes to think of scrolling over and, of course, there they were. 

I know this is a long post. I get chatty when I'm typing, in person people say I'm too quiet. Screenshots attached.
![Screenshot 2024-04-16 232525](https://github.com/xenocrat/chyrp-lite/assets/26007090/198e5511-94d4-44a0-b723-1eead5bea54a)
![Screenshot 2024-04-16 232550](https://github.com/xenocrat/chyrp-lite/assets/26007090/bc5ed1a8-dfb0-44fa-b7a4-66996c9ec9b9)

**Comment by xenocrat** [comment]
Hello there,

What web browser are you using, and what steps do you use in the browser to zoom? I can't reproduce this in Firefox or Edge, but I'd like to investigate further. Perhaps it's specific to one particular browser/settings combination.

**Comment by thatgrrl** [comment]
Sorry I didn't check back sooner. I use a variety of web browsers, mostly Opera now. But, it doesn't matter. Today I started writing a new post and noticed the screen was just the right width. Whatever you did, it worked great!

Thank you.

**Comment by xenocrat** [comment]
I'm glad it's fixed. Thank you for letting me know!
