### ISSUE TITLE
Importers fail to create new posts

### ISSUE THREAD

**Issue by kehugter** [xenocrat/chyrp-lite#25]
The relevant part of the error is

```
array_merge(): Argument #2 is not an array (/var/www/chyrp/includes/model/Post.php on line 230)
Backtrace

    includes/model/Post.php on line 230
    modules/importers/importers.php on line 296
```

I fixed it changing the order of the last 2 parameters in https://github.com/xenocrat/chyrp-lite/blob/09432a46a4b969fddd5b2a55afa10012b6cee673/modules/importers/importers.php#L286 (and changed `""` to `array()`).

It seems like all importers have the same issue, so just to confirm: am I doing something wrong? If not, I can PR a patch right away.

**Comment by xenocrat** [comment]
This is my fault. I see now that I broke the importers module when I removed trackback support [here](https://github.com/xenocrat/chyrp-lite/commit/1570d54e85ab592b50ce556982a1c4b278707265) a while ago. Chyrp Lite's native [importer](https://github.com/xenocrat/chyrp-lite/blob/develop/includes/controller/Admin.php#L1272) does it right. I'd be glad to receive a PR with these importers fixed.

The `false` is to disabled pingbacks – a good idea when batch importing. You can actually omit that last argument (the empty array) and Post::add will set a fallback value. The parameters can be seen [here](https://github.com/xenocrat/chyrp-lite/blob/develop/includes/model/Post.php#L158).

**Comment by kehugter** [comment]
> You can actually omit that last argument

Will do so. I'm relatively new to PHP and don't know the best practices, so I leaved it for consistency.
