### ISSUE TITLE
Search multiple keywords results in empty

### ISSUE THREAD

**Issue by cuixiping** [xenocrat/chyrp-lite#255]
Content: `"hello welcome to this world"`

Currently: Search `"hello"` or `"world"` can find the result, but search `"hello world"` can not.

Expected: search `hello world` can find the results which contain both `hello` and `world`.

**Comment by xenocrat** [comment]
Searching in Chyrp Lite does not use keword matching, it uses pattern matching - basically, a [SQL `LIKE` operator](https://dev.mysql.com/doc/refman/8.0/en/pattern-matching.html) (or `ILIKE` on PostgreSQL). If you search for "hello world", you are asking to be shown results containing this exact pattern, meaning that "hello welcome to this world" is not a match.

To find results containing "hello" and also "world" somewhere subsequent in the text, you would search for "hello%world". If you want to make this the default behaviour, you can easily create a simple module to respond to the `keyword_search` trigger filter and replace all occurrences of " " in the search query with "%". Keyword-style searching will result in more load on the server for each search query, so be careful with it.

If you are interested, I can show you example code for a module to do this.

**Comment by xenocrat** [comment]
You can read the wiki article [Making Your First Module](https://github.com/xenocrat/chyrp-lite/wiki/Making-Your-First-Module) for a general overview.

The module would look like this:

```
<?php
    class keywordSearch extends Modules {
        public function keyword_search($search, $query, $plain) {
            if (isset($search[1][":query"])) {
                # Capture non-keyword query text and params.
                $plain = end($search[0]);
                $query = $search[1][":query"];

                if ($plain == "post_attributes.value LIKE :query OR url LIKE :query") {
                    # Unset the existing plain query and params.
                    array_pop($search[0]);
                    unset($search[1][":query"]);

                    $words = explode(" ", trim($query, "%"));

                    foreach ($words as &$word) {
                        $word = "%".$word."%";
                    }

                    $search[0]["post_attributes.value LIKE ALL"] = $words;
                }
            }

            return $search;
        }
    }
```

You'll find lots of edge cases here - all the keywords need to be in the same attribute row of the database, so you won't be able to match a post with "hello" in the title and "world" in the body text.

Another option is to simply use another search engine that implements search the way you want it. The module below will redirect searches on the blog to DuckDuckGo. You could do the same thing for Google or whichever search engine you prefer.

```
<?php
    class ddgSearch extends Modules {
        public function main_search() {
            if (isset($_POST['query']))
                $query = $_POST['query'];

            if (isset($_GET['query']))
                $query = $_GET['query'];

            if (empty($query))
                Flash::warning(__("Please enter a search term."), "/");

            $url = parse_url(Config::current()->chyrp_url, PHP_URL_HOST);
            fallback($url, $_SERVER['SERVER_NAME']);

            $redirect = sprintf("https://duckduckgo.com/?q=site%%3A%s+%s",
                                urlencode($url), urlencode($query));

            redirect($redirect);
        }
    }
```

**Comment by xenocrat** [comment]
Interesting. Thank you for sharing. I don't want to implement this in Chyrp Lite because I want the SQL to be as portable as possible, but you could use this to achieve your desired result using the first module example I posted above. Something like this should work for the OR example:

```
<?php
    class keywordSearch extends Modules {
        public function keyword_search($search, $query, $plain) {
            if (isset($search[1][":query"])) {
                $plain = end($search[0]);

                if ($plain == "post_attributes.value LIKE :query OR url LIKE :query") {
                    array_pop($search[0]);
                    $search[0][] = "MATCH ( post_attributes.value ) AGAINST ( :query )";
                }
            }

            return $search;
        }
    }
```
