### ISSUE TITLE
Hyperlink issue

### ISSUE THREAD

**Issue by shinglesware** [xenocrat/chyrp-lite#259]
Thank you for all your efforts in this project. The application is awesome!

I noticed on v2024.02, a particular hyperlink behavior from the markdown seems to have changed from v2024.01. Is this a bug?

```
Sample markdown in v2024.01:
[Example](https://example.com) [[1](https://example.com/1.html) , [2](https://example.com/2.html) , [3](https://example.com/1.html)]

[![](https://example.com/picture.png)](https://example.com)

Results from v2024.01:
Example [1 , 2 , 3] <== where 'example', '1', '2', '3' are hyperlinks

picture.png image with a hyperlink
```

In v2024.02, the sequence of the `[[` seems to cause some parsing issues with the hyperlinks

**Comment by xenocrat** [comment]
Hello there,

Yes this is a regression. Thanks for reporting it! I'll investigate.

**Comment by xenocrat** [comment]
I've found and hopefuly fixed the issue. If you need an immediate fix, you can patch [LinkTrait.php](https://github.com/xenocrat/chyrp-lite/blob/develop/includes/lib/xenocrat/markdown/inline/LinkTrait.php) from the develop branch.
