### ISSUE TITLE
Call to undefined function filter_var()

### ISSUE THREAD

**Issue by mord0d** [xenocrat/chyrp-lite#262]
That's all I have.

It *may* happen when I go to `/admin`, but “Go back” and go to `/admin` does not throw an error again.

Tail of the `error_log.txt` does not help:

```
[21-May-2024 08:59:46 UTC] LOCALE en_US.UTF-8
[21-May-2024 09:00:03 UTC] LOCALE en_US.UTF-8
[21-May-2024 09:00:07 UTC] LOCALE en_US.UTF-8
```

Is my installation broken?

Or, if it *is* a bug, how can I detect and detain it?

**Comment by mord0d** [comment]
```
 # grep -r filter_var . 
./includes/lib/Twig/Cache/FilesystemCache.php:                if (\function_exists('opcache_invalidate') && filter_var(\ini_get('opcache.enable'), \FILTER_VALIDATE_BOOLEAN)) {
./includes/helpers.php:        if (!filter_var($string, FILTER_VALIDATE_IP))
./includes/helpers.php:            !filter_var(
 # 
```

**Comment by xenocrat** [comment]
Chyrp Lite requires the [data filter](https://www.php.net/manual/en/book.filter.php) extension to keep remote fetches safe from [SSRF](https://en.wikipedia.org/wiki/Server-side_request_forgery) attacks.

Two things Chyrp Lite does require `filter_var` at present: checking for updates and sending webmentions. If enabled in the settings, the update check happens once a day when an administrator enters the admin area and so it’s most likely this triggering your error.

Your choices are to add the data filter extension to your PHP build, or to disabled the update check and not use webmentions to avoid triggering the failure.

**Comment by mord0d** [comment]
>Chyrp Lite requires the data filter extension to keep remote fetches safe from SSRF attacks.

I didn't have this extension installed.

>Two things Chyrp Lite does require filter_var at present: checking for updates and sending webmentions. If enabled in the settings, the update check happens once a day when an administrator enters the admin area and so it’s most likely this triggering your error.

This is it! Both “Check for Updates” *and* webmention (via “Comments” module) are enabled.

Thank you!
