### ISSUE TITLE
install/upgrade.php should be deleted?

### ISSUE THREAD

**Issue by roughnecks** [xenocrat/chyrp-lite#266]
Hello,

as the tile says, should we delete those files after installation and upgrades?

Thanks

**Comment by xenocrat** [comment]
It's not necessary, but I would say yes, it is best to do so.

Once a configuration file exists, the installer will simply redirect to the main blog index if it is run again. The upgrader is safe to run at any time, but doing so repeatedly is resource intensive and could be used as a denial of service attack.

**Comment by roughnecks** [comment]
Thanks!
