### ISSUE TITLE
[Question] About comment's lenght sent to email..

### ISSUE THREAD

**Issue by roughnecks** [xenocrat/chyrp-lite#267]
Hello,

just a question: is there a reason why the comments posted on the blog that are sent to email do not contain the full text but only a few words? I can understand truncating them at some point but at the moment it's really like 10 words at best.

Thanks

**Comment by xenocrat** [comment]
Hello there,

I set the truncation to stay within the [78 char line length recommendation for plain text email](https://www.rfc-editor.org/rfc/rfc2822#section-2.1.1). I should probably revisit that choice. ;-)

**Comment by roughnecks** [comment]
Hey,

sorry, probably some confusion on my part while explaining.. It's not the single line length which I'm talking about, but the "whole" comment which is not reported in its integrity. If I write a comment with, let's say, 100 words, only the first 10 or something are emailed and then there are some final dots (to mean the comment continues..).

**Comment by xenocrat** [comment]
We're talking about the same thing. :-)

I limit the quoted comment to a single line of 60 chars, which would mean that, yes, you see about 10 words or so of the comment, followed by ...

I'll revisit this decision, and quote more of the comment.

**Comment by roughnecks** [comment]
Oh, alright then, thanks 👍

**Comment by xenocrat** [comment]
I've increased the comment excerpt length to the maximum the spec allows: 998 characters. Should be a noticeable improvement. :-)
