### ISSUE TITLE
Moved to Subdomain, Some Images Missing

### ISSUE THREAD

**Issue by thatgrrl** [xenocrat/chyrp-lite#268]
I moved Chyrp to a subdirectory and managed fine except for the images I uploaded. Some of them do show up and some do not. The difference is likely in how I uploaded them. I'm going to just go through and fix the link in each post. I'm expecting that to work. 

But, where would I change the files to unbreak this? I moved it from domain.com to domain.com/blog

**Comment by thatgrrl** [comment]
I was wrong. When I click on a post to edit it from the front end it comes back as not found. So I've messed up something more than just a few images. I haven't gone so far that I can't just put it back, make a back up of the posts and then install it fresh at the /blog instead. 

I'm just learning more left and right today. :)

**Comment by xenocrat** [comment]
If you move your blog after installation, you need to update _includes/config.json.php_ manually and change these lines to reflect the new location of the blog:

    "url": "http://example.com",
    "chyrp_url": "http://example.com",

Change to:

    "url": "http://example.com/blog",
    "chyrp_url": "http://example.com/blog",

If you've enabled [clean URLs](https://github.com/xenocrat/chyrp-lite/wiki/Supporting-Clean-URLs), you'll also need to edit the _.htaccess_, _caddyfile_, or _include.conf_ files to reflect the new location.

**Comment by thatgrrl** [comment]
Something is still off and I've mucked around trying to fix it myself. It couldn't export to the right destination and I don't want to figure out how or why. (I just don't know enough to explain to you even).

What file would all my posts be in so I can just move that over to a fresh installation? Or I could (hopefully) import the posts and pages files from the old into the new. 

Also, how much do you think the WordPress migration module could handle? I have a huge old site(s) which I've been merging into one location but I'd rather not keep WordPress as the software running it all. However, there are over 10,000 posts so its a pretty big migration. (None of the image files are working/there so that will help keep it a bit lighter). 

PS- I'm really liking markdown. I thought it would be complicated and hard for me to learn but its so much simpler. I even bought a little book to learn from but there isn't much to learn. I haven't needed the book. The little guide on Chyrp is all I need if I forget anything. Thank you for that.

**Comment by xenocrat** [comment]
Hello there,

What database adapter are you using: SQLite, MySQL, or PostgreSQL? If SQLite, the database Is a file stored on your server in the location you chose when installing. For the others, the database can be migrated just be using the same details for your re-install. You can find out this information by downloading _includes/config.json.php_ and looking at it in a text editor. The "sql" section of the file is what you need to look at.

Alternatively you can do an export from Chyrp Lite and import it into a new installation using Admin > Manage > Export and Admin> Manage > Import.

The Wordpress migrator hasn't been tested much, but it is/was working, so worth a go. I would use a clean Chyrp Lite install for this, so it's painless to wipe the slate clean if it doesn't work.

Glad to read that you are enjoying Markdown. I'm happy the guide is so useful. :-)

**Comment by thatgrrl** [comment]
My host uses MySQL. So I just need to give the fresh install the same database I had? I've never done that before. A lot less work that way. 

I was definitely going to use a different install for the WordPress migration. Nothing with WordPress involved is ever simple or easy. :)  I will be pretty surprised if it works. Not due to Chyrp, just the bloated WP files. I wonder if I can convert them to markdown before migrating. That would get rid of a lot of extra code, possibly.

**Comment by xenocrat** [comment]
Yep, if you give the existing database details to the Chyrp Lite installer, it will only do the necessary parts of the installation. This should result in your posts and pages all being there after the install.

**Comment by thatgrrl** [comment]
It worked. Thank you. :) I just had to re-add the modules and feathers and it was all back again. Like magic!
