### ISSUE TITLE
[bug] After a few comments get posted, CSS breaks somehow

### ISSUE THREAD

**Issue by roughnecks** [xenocrat/chyrp-lite#270]
Hi,

I don't have many info on this.. it just happened today when someone posted a few comments on my blog and I was going to reply.

https://i.imgur.com/XHpqG9N.jpeg

If I go along and comment on that, it's breaking the visualization as well. I'll update with a new image as soon as I reply.
At first I thought it was my custom theme, but then I set it back to Topaz and also deleted twig cache to no avail.

If you need the URL, just ask.
Thanks

**Comment by roughnecks** [comment]
I see that person using <code> and <blockquote> tags without even closing them.

**Comment by xenocrat** [comment]
If you have Markdown enabled on your blog, you might want to disallow all HTML in the comments settings. Limiting your commenters to Markdown will prevent unclosed blockquotes, code, etc.

**Comment by roughnecks** [comment]
Okay, I just did that! Thanks 👍
