### ISSUE TITLE
What is the way to specify the from address used in the emails?

### ISSUE THREAD

**Issue by AmritasyaPutra** [xenocrat/chyrp-lite#272]
For user registration the email are sent as www-data@domain.name where www-data was the user running my apache2 webserver. How can I explicitly specify what from address should be used?

I am using Chyrp Lite "Oak" with php8.3-fpm.

**Comment by xenocrat** [comment]
Hello there,

Emails are sent with the "From" field [set to your blog's contact email address](https://github.com/xenocrat/chyrp-lite/blob/2024.03/includes/helpers.php#L3344).
