### ISSUE TITLE
install.php doesn't do anything. 

### ISSUE THREAD

**Issue by naidje** [xenocrat/chyrp-lite#273]
Has anyone managed to get Chyrp Lite running on NearlyFreeSpeech? They have PHP and MySQL support out of the box, but I had to dig up an 8 year old step by step guide on their members only forum to get PostgreSQL installed. As far as I can tell I have all the dependencies installed properly.

I used the phpmyadmin panel to set up a database. I used CHMOD commands to give all the files the proper permissions as indicated by the installer page, then proceeded to fill out the correct information.

However, thats when I run into a wall. when i click the install button nothing happens. The page just refreshes and nothing gets installed. The error log doesn’t show anything happening at all, so I dont have anything to go on when it comes to troubleshooting. I have no idea whats causing it to not work.

The only thing i can think of is that my PostgreSQL installation is busted in some way, simce thats the one thing that wasnt preinstalled on the servers. But i dont really know how to confirm or deny this. There’s no error messages, and everytbing seems to be running properly as far as i can tell.

I’m just conpletely at a loss for how to get this working. :\

**Comment by xenocrat** [comment]
Hello there,

It's quite unusual for the installer to fail silently. Here's some things you can do to begin troubleshooting:

1. Inspect the file _error\_log.php_ in the base folder of your Chyrp Lite install. Anything interesting reported there?
2. Log into the PostgreSQL admin app and check if any of Chyrp Lite's tables have been created during the attempted installs.
3. Looks like NearlyFreeSpeech has MySQL and SQLite support - try an install using one of those instead. Does it work?

**Comment by xenocrat** [comment]
Closed due to lack of response.
