### ISSUE TITLE
Unable to Change Password

### ISSUE THREAD

**Issue by thatgrrl** [xenocrat/chyrp-lite#274]
I had to reset the password on a new install and that worked, once only. Some odd thing is going on with my web browser trying to save passwords. I think. Anyway, no problem just thought I would set a new one. I clicked "Help" and Chyrp said it was sending me the reset link. But... it took almost 2 days to arrive and then it tells me it is expired. I think the delay is due to my web host merging with another web host. Somehow the email to change the password came through a bluesky account, not mine. Anyway, that's the long version of the story.

Is there a way to change the password myself through phpmyadmin? I've done it that way (a few times) when WordPress mucked up and it was fairly simple. I looked at it with Chyrp but the same plan didn't work. I think I need to change something else with the 'varchar' part. That's my guess. 

Here is what I'm working with: https://www.wpbeginner.com/beginners-guide/how-to-reset-a-wordpress-password-from-phpmyadmin/ 

If that won't work for Chyrp please let me know what I can do. Thank you, as always. You really do give extra super support for Chyrp.

**Comment by xenocrat** [comment]
Hello there,

The password reset link will expire after 1 hour to avoid misuse. Ideally you should resolve your email delivery issues and then use the reset link within 1 hour, but if you want to edit the password directly you can do so in PHPMyAdmin as follows:

1. Select your Chyrp Lite database - the name was chosen by you during installation.
2. Browse the table "users"
3. Find your entry in the table, using the "login" column to guide you.
4. Change the data for your entry's password column to `$6$rounds=50000$wceapVGNDcHUNSYc$3aGWRuvEX0DIKe6uK9VTxnMpQJOs8iC8gl9ytZ0A9JCOcw7bHij60hU4kcVjtHVK3B1/0wfatCFxASR6fvbjn0`. __Do not use the md5 function__ - Chyrp Lite does not use md5 hashing for passwords.
5. After changing the data, your password is now "password". I encourage you to log in and change it to something more secure immediately. ;-)

**Comment by thatgrrl** [comment]
That worked. Thank you.
