### ISSUE TITLE
Update from Chyrp to Chyrp-lite

### ISSUE THREAD

**Issue by Paul-Reed** [xenocrat/chyrp-lite#3]
Is there a route from Chyrp tp Chyrp-lite?

**Comment by xenocrat** [comment]
You can follow the upgrade procedure [here](https://github.com/xenocrat/chyrp-lite/wiki/Requirements-and-Procedures#upgrading), basically it's the same as a regular Chyrp-to-Chyrp upgrade. Running upgrade.php will take care of changes to the database to support Lite features such as page permissions and upgraded password hashing.

Feather support varies a bit, but modules and themes should be fully compatible. I think you'll be able to revert to Chyrp if you wish after testing Lite, but nonetheless I highly recommend you backup your database before you begin.

**Comment by Paul-Reed** [comment]
Thanks Daniel, I'll give it a try after my next full system backup.
Paul
