### ISSUE TITLE
Activation Email Not Recieved

### ISSUE THREAD

**Issue by kreativmind** [xenocrat/chyrp-lite#32]
I have attempted to register an account for myself on Chyrp Lite blog and I get the message

We have emailed you an activation link

But I never received an email in my inbox nor junk folder. Is there a config file I need to make sure email settings are setup in? I haven't had much luck finding out the reason why nothing is received.

**Comment by xenocrat** [comment]
Chyrp's correspondence features use the PHP [`mail()`](http://php.net/manual/en/function.mail.php) function, which in turn will be using the `sendmail` shell command on most servers.

If your server is not configured to send mail, in theory you should receive an error message but more often what happens is `sendmail` successfully spools the email (accepts it for sending) but has not been adequately configured to do the actual sending, so the email just sits in the server's mail spool forever.

How to resolve this problem depends on your particular server. Firstly you need to discover which mail transfer agent you have available – often this will be [sendmail](https://en.wikipedia.org/wiki/Sendmail) or [postfix](https://en.wikipedia.org/wiki/Postfix_(software)) – and then find a how-to that will walk you through the configuration process.

**Comment by kreativmind** [comment]
Thanks bro. I am going to check into it. I am hosting with TMDHosting and will see. I know I have a valid email account setup for the domain so not sure what it could be but will find out. Appreciate the feedback.
