### ISSUE TITLE
No Pages Menu Using Sparrow Theme

### ISSUE THREAD

**Issue by kreativmind** [xenocrat/chyrp-lite#33]
When I activate the default Blossom theme, I can see a separate pages menu with the pages listed that I have created. However, when I activate the Sparrow theme which I use, there is no pages menu displayed. Only menu displayed is:
     Email Feed Archive Admin Controls Log out

**Comment by xenocrat** [comment]
That's expected behaviour. Sparrow is intended as a tumbleblog theme (Tumblr-like) with an extremely simple layout. It doesn't offer a pages list, enumerated archives, or recent/related posts.

**Comment by kreativmind** [comment]
Ahh...okay. Thank you for clarifying that. I am going to try and add the pages menu to it. I like that theme the most out of Blossom, Topaz, and Sparrow. Not sure if I will be successful but will definitely try.
