### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by kreativmind** [xenocrat/chyrp-lite#34]
I received this message right after it installed and told me to login.

The line of code is:
foreach (Config::current()->enabled_modules as $module)

Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Undefined property: Config::$enabled_modules (/mysite/includes/helpers.php on line 705)
Invalid argument supplied for foreach() (/mysite/includes/helpers.php on line 705)
Please consider setting a stronger password for your admin account.

Chyrp Lite has been installed
What now?

**Comment by xenocrat** [comment]
Thanks for the report. That's the autoloader complaining because there is no enabled_modules config setting until the installation is done; I'll add some conditional code to make sure that doesn't happen.

**Comment by kreativmind** [comment]
Sounds great. Just wanted to let you know. One other thing, I don't know much about Twig...are we looking at getting any new themes anytime soon? Something little more like a medium inspired theme with ability to have a header image would be awesome.

Thanks

Jeremy

Date: Fri, 1 Jul 2016 14:02:54 -0700

**Comment by xenocrat** [comment]
Next few releases after Chestnut should be (I hope!) smaller bug fix releases, so I might look to create a new theme later this year.

**Comment by kreativmind** [comment]
Awesome


Jeremy Monroe






On Fri, Jul 1, 2016 at 4:19 PM -0500, "Daniel Pimley" <notifications@github.com> wrote:





Next few releases after Chestnut should be (I hope!) smaller bug fix releases, so I might look to create a new theme later this year.

---
