### ISSUE TITLE
Added Features

### ISSUE THREAD

**Issue by kreativmind** [xenocrat/chyrp-lite#37]
@xenocrat Here are some features I would like to see implemented.
1. More Themes
2. Ability to change what is displayed on the menu from the admin panel (customizable menu)
3. Have a grouping option that will allow admin to add page links so that can group by audio, photos, even certain collections of photos based on categories or tags that the members add to their uploads when posting. Like have nature category group photos tagged with nature, animals, etc and a page link can then be created titled Nature and it displays those photos. Also, can create a page titled New or Recent and it displays the most recent within the past week, etc.

Sorry if I am posting this in the wrong spot as I wasn't sure where else to post it. Remember we used to have the forum on the old site

**Comment by xenocrat** [comment]
Thanks for taking the time to write this down. I will give some thought to possible solutions.

**Comment by kreativmind** [comment]
Thanks for the consideration.

**Comment by xenocrat** [comment]
Some initial thoughts:

1. Probably I will add one more theme (based on Sparrow) for the next release.
2. A bit of work in a text editor is the easiest way to accomplish this. I understand that editing a twig file is not everyone’s idea of an easy task, but Twig makes small customisations like this doable without much experience. Building a fully-featured admin UI for this is a complex task and, I think, at odds with Chyrp Lite’s mission of remaining lean. It would also mean that themes must cede this control, and I think it’s better that the theme gets to decide what navigation options to expose. 
3. Some of this can be done with the search function. For example, if you enter “feather:video;” as your search term, all posts created with the video feather will be displayed, and if you enter “feather:video; animals” then all video posts with the word animals in their title or body will be displayed. You can publish a link to the search results page that is displayed when you enter that search term, or you can create a snazzy URL by adding a new [custom route](https://github.com/xenocrat/chyrp-lite/wiki/Routes-and-Controllers#adding-custom-routes-manually): `"videos": "search;query=feather:video”`. You can’t build a search term for a combination of certain categories, tags, and feather types; the easiest solution in that case is to step in as administrator and add your own tag to each of the posts for this purpose (e.g. “nature collection”).

**Comment by kreativmind** [comment]
I understand what you mean about Twig. The grouping option I was referring to was more for the end user reading the blogs. They wouldn't know to search for feathers and so forth. I guess I will have to read it a few times again to see exactly what you mean. My brain isn't exactly comprehending it for some reason.
