### ISSUE TITLE
Add post display Error

### ISSUE THREAD

**Issue by luotaiping** [xenocrat/chyrp-lite#39]
My mysql **sql_mode** is **TRADITIONAL** mode, so when adding a new post will be wrong:

**Database error: Incorrect datetime value: '0000-00-00 00:00:00' for column** 

I have modified my **sql_mode for ANSI mode**, the problem is temporarily resolved, hoping to solve the problem in the code.

**Comment by xenocrat** [comment]
Thank you for the report. Please take a look at [this commit](https://github.com/xenocrat/chyrp-lite/commit/a85d1e4b41ac4fce58dbfe53ad1396dd502a6ce3) with a patch for SQL.php. I hope this will solve your problem.

**Comment by luotaiping** [comment]
OK，It's worked.Thanks you response!
