### ISSUE TITLE
Uploader Feather behavior on edit post

### ISSUE THREAD

**Issue by hasslerf** [xenocrat/chyrp-lite#4]
Recently used the uploader Feather a lot to post a Gallery for every day of a really long holiday. Everytime I want to edit the Content I have to reupload the Fotos. Please change to only delete Uploads when there are new uploads or the post is updated. TIA.

**Comment by xenocrat** [comment]
Hello there! When you edit posts made with the photo/video/audio/uploader feathers, if you don't select any new files then the originals will be retained. Let me know if you are seeing different behaviour, and I will investigate the cause.

**Comment by xenocrat** [comment]
Update: I think I've discovered the issue. You can expect to see the fix in the next release, coming very soon.

**Comment by hasslerf** [comment]
Reproduction of the problem: It happens, when you first edit in Frontend-Mode and click edit again - you are redirected to "/admin/?action=edit_post&id=xxx" there you only get the Save Button and afterwards an "/admin/?action=update_post" Error with: "Error Failed to upload file." Thanks!
