### ISSUE TITLE
PHP7 probelm

### ISSUE THREAD

**Issue by HenningBertram** [xenocrat/chyrp-lite#40]
I have tried to install Chyrp Lite on Ubuntu 16.04 where PHP7 is the default install. I do, however, get this error:

session_write_close(): Session callback expects true/false return value

I hve tried to figure what is going on, but -alas- it is beyond my PHP skills.

**Comment by xenocrat** [comment]
Thank you for the report. It looks like PHP 7 expects the session handler to return `true`, whereas PHP 5 doesn't care what is returned. Please try replacing your file Session.php with the version from [this commit](https://github.com/xenocrat/chyrp-lite/commit/f61436caf6313f991b5974b0562d7f3bb0de56c6) and let me know if that resolves the problem.

**Comment by HenningBertram** [comment]
Works! Thank for your swift response. For a moment there I thought I has to go back to WordPress or something...

**Comment by xenocrat** [comment]
I'm glad to save you from that fate. ;-)

A lot of work has been done to make Chyrp Lite ready for PHP 7 but I haven't yet been able to test it, so I'm very grateful for this report.
