### ISSUE TITLE
WYSIWYG inserting attempt question

### ISSUE THREAD

**Issue by Dextrolain** [xenocrat/chyrp-lite#43]
This is not exactly a chyrp lite issue, but I just don't know where else to ask.

I heard that there are no plans on adding wysiwyg editor as a module, but still I decided to try something myself. 
Since I'm not a programmer I tried to insert a cdn ckeditor at least.
As far as I understand, main .js script call should go to  ../admin/layouts/default.twig next to other scripts in the head.
And the CKEDITOR.replace( 'body' ); function should go after the textarea in ../admin/partials/post_fields.twig and page_fields.twig
I've been trying different ways of inserting, different wysiwyg editors and same problem - just nothing happens, textarea stays the same.
Just can't get my head around this.
I guess all this requires something more to be inserted to chyrp lite. Or maybe I just don't see something obvious.
Sorry if the question is too unrelated, but it would be just awesome if you could give any hints on this subject even though it's not that much about chyrp itself :3

**Comment by xenocrat** [comment]
Best way to do this is using a module, so that you don't have to redo all your modifications if you upgrade your Chyrp Lite installation.

Here's a [module](https://github.com/xenocrat/chyrp-lite/wiki/Anatomy-of-a-Module) I just made that successfully adds the editor to the page by responding to the "admin_head" [trigger](https://github.com/xenocrat/chyrp-lite/wiki/Introduction-to-Triggers):

    <?php
        class Ckeditor extends Modules {
            public function admin_head() {
                $config = Config::current();
    
                if (!$config->enable_markdown)
                    return;
    
                echo "\n".
                     '<script src="https://cdn.ckeditor.com/4.7.0/standard/ckeditor.js" type="text/javascript" charset="UTF-8"></script>'."\n".
                     '<script type="text/javascript">'."\n".
                     '    $(function() {'."\n".
                     '        $("textarea[data-markdown]").each(function() {'."\n".
                     '            CKEDITOR.replace( $(this)[0] );'."\n".
                     '        });'."\n".
                     '    });'."\n".
                     '</script>';
            }
        }
    

You can copy that code, and save it in a file called "ckeditor.php". Put the file in a folder also called "ckeditor" in your modules folder. Well done, you have created a module!

**Comment by xenocrat** [comment]
Quick note: this example copies a lot of code from the [SimpleMDE module](https://github.com/xenocrat/chyrp-lite/tree/develop/modules/simplemde), so it checks if Markdown is enabled on the site before it does anything. You can remove this if you prefer, and also have CKEditor added to every `<textarea>` by changing `$("textarea[data-markdown]")` to `$("textarea")`, or target just the write and edit pages using `$("#write_form textarea, #edit_form textarea")`. Hope that helps.

**Comment by Dextrolain** [comment]
Wow, that works perfectly fine and even better!
Thank you a lot for your work both on this module and chyrp lite itself, everything is just great.
