### ISSUE TITLE
Comment line breaks

### ISSUE THREAD

**Issue by dahliadahlia** [xenocrat/chyrp-lite#44]
I wasn't sure where to put this since this isn't a direct issue with Chyrplite so much as a question.

I'm using the Sparrow theme on a test site and noticed comments don't retain linebreaks. The comment text is printed out in a single line / paragraph.

Is there a way to have comments preserve linebreaks via CSS or some other method?

**Comment by xenocrat** [comment]
If you have Markdown formatting enabled for blog content (Admin > Settings > Content > Markdown) then you can start a new paragraph in a comment with a double line break when writing the comment. 

Alternatively you can modify the theme file _themes/sparrow/content/comment.twig_ and enclose the line `{{ comment.body }}` in [`<pre>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre) tags if you want to exactly preserve whitespace in comments, including line breaks.

**Comment by dahliadahlia** [comment]
Hello Xenocrat, thank you for the fast response!

I honestly hadn't even thought about wrapping the comments in <pre> tags, that's pretty genius! I'll go that route, since my target audience generally doesn't know what markup is. 

Thank you once again for the help. I love Chyrplite and hope it's around for a long time.
