### ISSUE TITLE
Can't import/export posts, pages, groups, users.

### ISSUE THREAD

**Issue by vybhav93** [xenocrat/chyrp-lite#45]
Please help me with the above issue. I can't import/export posts, pages, groups, users. Error message  'Access Denied
Invalid security key.'

**Comment by xenocrat** [comment]
Another user recently had a similar problem, reported in issue #42. Please try using a different browser with default settings and let me know if the error persists.

**Comment by vybhav93** [comment]
Thanks a lot... It helped me..
