### ISSUE TITLE
Guest - Front page Posting Form

### ISSUE THREAD

**Issue by roywikan** [xenocrat/chyrp-lite#50]
Hello.. I love Chyrp Lite.
This is just a question. I want to use chyrplite as  a guestbook function. 
Anybody knows how to create simple guest front page post with Maptcha enabled?
The Guest **does not need** to login/register first. Maptcha is needed to be solved by Guest. Default form submission is "Denied" mode. 
Thanks for any comment / ideas .

**Comment by xenocrat** [comment]
Thanks for the kind words.

There's a few different ways you might implement a guest book, depending on how you want it to behave. Perhaps the simplest and most flexible way is to create a module to generate a HTML form on demand. Here is a bare bones implementation that adds a guest book submission form to any post or page that contains the text `<!-- guestbook -->`.

    <?php
        class Guestbook extends Modules {
            public function __init() {
                # Replace comment codes before Markdown filtering (priority 5).
                $this->setPriority("markup_text", 4);
            }

            public function markup_text($text) {
                if (!is_string($text))
                    return $text;

                $form = '<form action="'.Config::current()->chyrp_url."/?action=guestbook".
                        '" method="post" accept-charset="UTF-8">'."\n".
                        '<label for="guest_name">'.__("Your Name", "guestbook").'</label>'."\n".
                        '<input type="text" name="guest_name" value="" id="guest_name_field" maxlength="250">'."\n".
                        generate_captcha().
                        '<label for="guest_note">'.__("Your Note", "guestbook").'</label>'."\n".
                        '<textarea name="guest_note" id="guest_note_field"></textarea>'."\n".
                        '<input type="hidden" name="hash" value="'.token($_SERVER['REMOTE_ADDR']).'" id="hash">'.
                        '<button type="submit">'.__("Submit", "guestbook").'</button>'.
                        '</form>'."\n";

                return preg_replace('||i', $form, $text);
            }

            public function main_guestbook($main) {
                if (!isset($_POST['hash']) or $_POST['hash'] != token($_SERVER['REMOTE_ADDR']))
                    Flash::warning(__("Invalid authentication token."));

                if (empty($_POST['guest_name']))
                    Flash::warning(__("Your name cannot be blank.", "guestbook"));

                if (empty($_POST['guest_note']))
                    Flash::warning(__("Your note cannot be blank.", "guestbook"));

                if (!check_captcha())
                    Flash::warning(__("Incorrect captcha response.", "guestbook"));

                if (!Flash::exists("warning")) {
                    $output = "Name: ".$_POST['guest_name']."\n".
                              "Note: ".$_POST['guest_note']."\n\n";

                    @file_put_contents(MAIN_DIR.DIR."guestbook.txt", $output, FILE_APPEND);

                    Flash::notice(__("Thanks for writing in the guest book!", "guestbook"));
                }

                redirect(oneof(@$_SESSION['redirect_to'], "/"));
            }
        }

You would save this as _guestbook.php_ and put it in a folder named _guestbook_ inside the modules folder of your Chyrp Lite install, then enable it in the Extend tab of the admin console.

When the visitor successfully defeats the MAPTCHA, their name and note will be added to a file named _guestbook.txt_ saved in your install directory. If you want to display the guest notes to visitors and/or use a database to store them, you should look at some bundled modules for direction – that's a bit too complicated for me to cover here. In particular you would need to make sure you sanitised the input if you planned to display these notes on the page, to avoid code injection.

I hope that helps to get you started!

**Comment by roywikan** [comment]
I will try that, thanks @xenocrat !
