### ISSUE TITLE
Feature request: Recent posts module

### ISSUE THREAD

**Issue by starshine531** [xenocrat/chyrp-lite#52]
The only thing I'm looking for that's not already in the module folders is a section for recent posts. 
Is there is already a way to do this with the current modules? If not, I could write my own, but it does seem like this would be something people would frequently want in a blog and shouldn't be very difficult to implement. If I do end up creating my own, I'll let you know.

**Comment by xenocrat** [comment]
The [Theme](https://github.com/xenocrat/chyrp-lite/blob/master/includes/class/Theme.php#L139) class provides a method for getting a list of recent posts, which is used by some themes (Blossom, Topz) to show recent posts in the sidebar. The method defaults to the 5 most recent posts but you can supply your preferred limit.

If you want to display those posts in an index, you'll have to build a simple module to act as a [responder](https://github.com/xenocrat/chyrp-lite/wiki/Routes-and-Controllers#how-do-routes-work) (my module [Alphabetize](https://github.com/xenocrat/chyrp-alphabetize) is a good template for this) but if you just want to display them somewhere in a menu or list on your site then you can use some Twig code similar to this:

    {% for post in theme.recent_posts() %}
     <a href="{{ post.url() }}">{{ post.title() | striptags | normalize | oneof(post.slug) | truncate(30) }}</a>
    {% endfor %}

I hope that helps!

**Comment by starshine531** [comment]
Yes, that will do. Thank you!
