### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by hypervtechnics** [xenocrat/chyrp-lite#54]
I copied the english chyrp.pot and did my translation then I copied it to /includes/locale/de_DE/LC_MESSAGES and named it chyrp.pot. In settings you then see german as an option. But when I select it and click update the language doesnt change.

**Comment by xenocrat** [comment]
Hello. A few things are needed for translations to work:

1. Your server must support the chosen locale.
2. Your PHP environment must be built with [GNU gettext](http://php.net/manual/en/gettext.installation.php) support.
3. You must create a compiled translation (ends in .mo extension), using the .pot file as the basis.

I recommend [Poedit](https://poedit.net) for creating and compiling translations. You can find information on GNU gettext [here](https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/gettext.html).

**Comment by hypervtechnics** [comment]
Is gettext not included by default?
Okay I will try Poedit.

**Comment by xenocrat** [comment]
gettext is not enabled by default, but it has been commonly enabled in the installations I've seen. I'll improve the wiki to make the requirements clear. Thanks for your question and please do let me know if you run into any bugs or problems.

**Comment by hypervtechnics** [comment]
Where do I put the *.mo file?

**Comment by xenocrat** [comment]
/includes/locale/de_DE/LC_MESSAGES/chyrp.mo

**Comment by hypervtechnics** [comment]
I put it there but still no german language. Is there a gettext module I have to install/enable or how do I get gettext support under Ubuntu + Apache?

**Comment by xenocrat** [comment]
Let's test if you have all the requirements. Make a file on your server named _locale.php_ and put this code in it:

    <?php
        $putenv = @putenv("LC_ALL=de_DE");
        $locale = setlocale(LC_ALL, array("de_DE.UTF-8",
                                          "de_DE.utf-8",
                                          "de_DE.UTF8",
                                          "de_DE.utf8",
                                          "de_DE"));

        $gettext = function_exists("dgettext");
    
        echo "putenv allowed: ".($putenv ? "yes" : "no")."; ";
        echo "locale support: ".(!empty($locale) ? '"'.$locale.'"' : "no")."; ";
        echo "gettext extension: ".($gettext ? "yes" : "no");

Now visit _locale.php_ with your web browser and it will report the results. You'd want to see:

    putenv allowed: yes; locale support: "de_DE.UTF-8"; gettext extension: yes

Installation info for PHP's gettext extension is [here](http://php.net/manual/en/gettext.setup.php) and information on installing locales for Ubuntu is [here](https://askubuntu.com/questions/76013/how-do-i-add-locale-to-ubuntu-server).

If your result looks good, there could be a problem with your translation file. Also remember the core "chyrp" domain is not responsible for most of the text you see on blog pages; the theme's translation domain handles most of this text.

**Comment by hypervtechnics** [comment]
I have currently no time to do this. Will try it at weekend. So please don't think I do not answer 😆

**Comment by hypervtechnics** [comment]
[Translation.zip](https://github.com/xenocrat/chyrp-lite/files/1511887/Translation.zip)
Sorry for the late reply... I just uploaded both files I created. The locale.php returns exactly those values it has to return. Maybe there is a problem with .mo file?
I placed it at <chyrproot>/includes/locale/de_DE/LC_MESSAGES/de_DE.mo
Anyways something seems to went wrong during compilation. And I cant fix it. Could you compile the pt file on your setup and share it so I may try to replace the current (empty) version with it?

**Comment by xenocrat** [comment]
There's a couple of mistakes. Firstly the file needs to be named after the domain, so in this case it should be named "chyrp.mo". Secondly in the source file you have replaced the message IDs; what you need to do is leave the IDs in English and put your translation between the quote marks on the next line, e.g.

    msgid "Error"
    msgstr "Fehler"

I've fixed the problems and made a version that works in my test environment: [de_DE.zip](https://github.com/xenocrat/chyrp-lite/files/1515874/de_DE.zip)

I noticed during my testing that translation changes didn't always apply immediately when I changed the locale, so wait a little while after applying this to your installation before declaring success or failure. The delay isn't caused by Chyrp as far as I can tell, it seems to be something going on within gettext.

I hope that helps! Would you consider allowing this translation to be included in the next release of Chyrp Lite?

**Comment by hypervtechnics** [comment]
Okay now it works :) In my setup there was no delay.

Anyways of course you can include the translation in the next release.

Thank you very much.

**Comment by xenocrat** [comment]
That's great news. I'm glad we were able to get it working for you. Thank you for your contribution!

**Comment by hypervtechnics** [comment]
I know this is closed: But here is the translated file for the blossom theme as not all strings seem to be translated by the base file. In the future I will also translate all of the other themes. Also the settings are somehow not fully translated (Only headers but not the settings themselves).
[blossom.zip](https://github.com/xenocrat/chyrp-lite/files/1522688/blossom.zip)

**Comment by xenocrat** [comment]
Thanks! Most of the strings for the admin console are stored in the “admin” translation domain. You can find this in *admin/locale/*.
