### ISSUE TITLE
Post sort order

### ISSUE THREAD

**Issue by altexa** [xenocrat/chyrp-lite#55]
Imported a list of posts from Chyrp.
Most-recent posts are listed at the top - this is fine.

Found a typo in the first post, edited it - leaving original timestamp.  Save post.
It is now listed at the bottom (i.e. invisible).  Also in admin, this post is last in the list.

Can posts be sorted automatically by timestamp descending?

**Comment by altexa** [comment]
![image](https://user-images.githubusercontent.com/34234230/33545751-68a35106-d8df-11e7-84fc-4ffb6597a8a5.png)

**Comment by altexa** [comment]
This is the front page of the blog.  As loaded by default.
Note recent posts list the two "what is backup software" posts (this is correct) - but the blog itself shows "Volume Shadow Copy" as the first post, while it should be third:

![image](https://user-images.githubusercontent.com/34234230/33547457-682a0df0-d8e4-11e7-8c8b-3dbdad7a2c14.png)

**Comment by xenocrat** [comment]
Perhaps your post "Volume Shadow Copy" is pinned? This would cause it to appear above other posts in the blog index and the admin area. The usual sort order for both blog and admin area is `pinned DESC, created_at DESC, id DESC`.

What happens to the sort order if you edit some of the other posts?

**Comment by altexa** [comment]
Thanks for your reply - nothing is pinned.

Here's an extract of the database:

![image](https://user-images.githubusercontent.com/34234230/33596530-4c6aed6a-d99c-11e7-926b-f9fa93ba4f5c.png)

and the rest of the lines:

![image](https://user-images.githubusercontent.com/34234230/33596561-66fb75f0-d99c-11e7-8487-5ab4593a982c.png)


The updated_at is only filled for the posts I modified...don't know if this is linked to the fact that everything was imported.

**Comment by altexa** [comment]
....or maybe the sort problem is that the pinned field was not updated when the data was imported, and hence is null...and the update sets it to 0, and null comes before 0 in a sort

**Comment by xenocrat** [comment]
Yes I think that may be the answer. Chyrp Lite will consider any “falsey” value as unpinned, but the database is prioritising null above 0 when it sorts the query results. The recent posts in the blog sidebar are not affected because the sort order for those results does not consider pinned status.

**Comment by altexa** [comment]
I'll update the DB manually, setting 'pinned' to 0 everywhere.  Might be an idea (if possible) to set pinned to 0 on import, if not specified in the import file.

Thanks again

**Comment by altexa** [comment]
Confirmed, with a 0 in all lines, the sort is correct

**Comment by xenocrat** [comment]
Yes, I’m going to look into this later today. The import method is casting the pinned value from the XML document to boolean but the normal behaviour for added/updated posts is to cast the value to integer, and I think this is causing different handling when sent to the database. Thanks for the report!

**Comment by altexa** [comment]
The thanks are mine ;)
