### ISSUE TITLE
OAUTH2 Signup/Sign In

### ISSUE THREAD

**Issue by roywikan** [xenocrat/chyrp-lite#59]
_Just a question or idea :_

**How to add oauth2 registration/login/commentator ?**

like sign up/login using Google+ credential .

**Comment by xenocrat** [comment]
There's plenty of [triggers](https://github.com/xenocrat/chyrp-lite/wiki/Introduction-to-Triggers) in the codebase that would allow you to do something like this. In particular, the [visitor](https://github.com/xenocrat/chyrp-lite/blob/v2018.01/includes/common.php#L358) trigger can be used for transparent login, the [user_register](https://github.com/xenocrat/chyrp-lite/blob/v2018.01/themes/blossom/forms/user/register.twig#L17), [user_login](https://github.com/xenocrat/chyrp-lite/blob/v2018.01/themes/blossom/forms/user/login.twig#L12) and [user_authenticate](https://github.com/xenocrat/chyrp-lite/blob/v2018.01/includes/controller/Main.php#L618) triggers can add extra elements to the register/login forms and authentication process.

You can even overload MainController's login responder entirely and handle the login process yourself by creating a module with a `main_login()` trigger responder.

I don't know much about OAuth2 or OpenID but I imagine what you'd want to do is add an element to the login form, authenticate with the remote server when the form is submitted, and use the returned data to create a new user in your blog's database if authentication is successful.

**Comment by xenocrat** [comment]
For example:

    <?php
        class LoginOverload extends Modules {
            public function main_login($main) {
                error_log("My totally awesome module was called!");
    
                if (!isset($_POST['my_oath_login_field_added_to_the_form_using_a_trigger']))
                    return false;
    
                // Do OAuth stuff.
            }
        }

If you put this into a module, this responder will capture all visitor requests for the login page. If there's no OAuth input field to work with (which you would add to the login form by responding to the `user_login` trigger), this overload responder will just hand back to the regular login responder in MainController.
