### ISSUE TITLE
Updated Feathers

### ISSUE THREAD

**Issue by mtech** [xenocrat/chyrp-lite#6]
I have updated the feathers to follow your format for Chyrp-Lite. I thought I had credentials once to push them to you but it keeps failing stating that I don't have permission.

**Comment by xenocrat** [comment]
I don't know what could be preventing the pull request, however File feather has been replaced by Uploader, and Chat feather is deprecated – I consider it a very niche requirement to post a chat log as a blog post, and in such as case Text feather does the job.

I've worked on the Tumblr import code a bit and removed the need for Chat feather.

**Comment by mtech** [comment]
I am not sure. Still haven't figured out the pull request issue. Okay...so you will no longer need me to upload the file feather nor chat feather I updated. Sounds good. Thanks for the updated information.

**Comment by xenocrat** [comment]
I will work on an upgrade process to migrate any posts made with those deprecated Feathers to Text/Uploader. Should be helpful for any Chyrp users coming over. ;-)

**Comment by mtech** [comment]
I agree. Will be great for those switching over.

**Comment by xenocrat** [comment]
[Your wish is my command](https://github.com/xenocrat/chyrp-lite/commit/c7da5a67b347603011d615c15ea5e38cb3e489ab). =)
