### ISSUE TITLE
How to define categories?

### ISSUE THREAD

**Issue by Torsten-K** [xenocrat/chyrp-lite#62]
I activated the categories module, but I cannot find any opportunity to define categories. Under _Manage_ in the admin panel, there is not such a tab.

Apache 2.4 (on CentOS, I guess) with PHP 7.1.

**Comment by xenocrat** [comment]
Hello there. You need to give your group permission to manage categories after you enable the module. You can do this by visiting Admin > Manage > Groups, then edit the group your account belongs to and make sure the group has the newly added Manage Categories permission. Once that's done, you will find a new tab for Manage > Categories.

**Comment by Torsten-K** [comment]
Thanks for your quick reply. Following your advice did the trick. I am just wondering why even the admin group needs this manual intervention, but now I know, and everything’s fine.

By the way, I like Chyrp Lite very much, as it is lightweight and easy to use.

**Comment by xenocrat** [comment]
Thank you for the kind words!

I know it's a bit confusing that you have to enable the new permissions for your group when you enable a module, but I hope that understanding more about Chyrp's permission system will make it clearer.

Although a fresh install comes with a group called "Admin", there's really nothing special about this group – the "Admin" group has been created with some permissions (such as "change settings") that other groups don't have, but it's totally possible for you to create more than one group that has some or all of the permissions you might think of as belonging to an administrator. Modules have no way to tell which groups you've created that you want to be treated as administrators, and this is why you have to configure things manually when a module adds some new permissions. I hope that helps!

**Comment by Torsten-K** [comment]
Ah, okay, thanks for the clarification.

**Comment by shukebeta** [comment]
Fortunately I found this closed issue before I submit a new one. Keep it opened may help more, I honestly think :)

**Comment by xenocrat** [comment]
Thanks for the input. I will reopen the issue so it is easier to find.

**Comment by thatgrrl** [comment]
Worked for me too. Thank you.
