### ISSUE TITLE
Specific blog post URL variable for social "Share" buttons

### ISSUE THREAD

**Issue by Dextrolain** [xenocrat/chyrp-lite#65]
I have another small question, hope you could help. 
Is there any way I could use post.url variable for facebook share widget for example?
So that clicking the Share button on blog post body displayed on index page would share the specific post url automatically.

I tried adding something like this to the code:
```
<script>var postUrl = 'post.url';</script>
<div class="data-href='" + postUrl + "'><a href="https://www.facebook.com/sharer/sharer.php?u=" + postUrl + ">Share</a></div>
```
Full code:
```
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var postUrl = 'post.url';
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/ru_RU/sdk.js#xfbml=1&version=v2.12';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-share-button" data-href='" + postUrl + "' data-layout="button_count" data-size="small" data-mobile-iframe="false"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=" + postUrl + ";src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div>
```

But I guess I'm doing it way too wrong.

**Comment by xenocrat** [comment]
You need `post.url()` here which is an absolute URL for the post, e.g. http://www.example.com/2018/02/19/my-first-post/. You can only access this using the Twig template engine, so you would need to have Twig output the URL somewhere in the page source for your JavaScript to discover.

Alternatively you can add the button your theme's _content/post.twig_ template:

    <div class="fb-share-button" data-href="{{ post.url() | fix(true) }}" data-layout="button_count" data-size="small" data-mobile-iframe="false">
      <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u="{{ post.url() | fix(true) }}";src=sdkpreparse" class="fb-xfbml-parse-ignore">
        Share
      </a>
    </div>

**Comment by Dextrolain** [comment]
Thanks for the tip. Appreciate your help.
