### ISSUE TITLE
url issue when hosted behind a reverse proxy

### ISSUE THREAD

**Issue by harikarunakar** [xenocrat/chyrp-lite#66]
The url parameter should be available in the admin setup (initial).
At the moment after setting up the database and admin details, the server redirects to localhost:{apachePort}.
The Chyrp URL should be available in the setup.

Time being this can be overcome by setting up parameters in the json file.

**Comment by xenocrat** [comment]
Thanks for the report. I've been thinking for a while that it might be wise to surface the Chyrp URL during installation. I will make this change for the next release.
