### ISSUE TITLE
Disabling lightbox/image protection for a specific image

### ISSUE THREAD

**Issue by Dextrolain** [xenocrat/chyrp-lite#68]
Hi again :3 
I was just wondering if there is an easy way to disable image protection for a specific image or page or maybe for a specific container?

**Comment by xenocrat** [comment]
There is now. ;-)
If you patch with the commit referenced above you can disable protection for an individual image by giving it the class name `suppress_protect`. Let me know if you have any problems.

**Comment by Dextrolain** [comment]
That works perfect ^__^ Thanks a lot, appreciate your help.
