### ISSUE TITLE
Edit Menu Items

### ISSUE THREAD

**Issue by nathan93** [xenocrat/chyrp-lite#69]
Hello!

I am wondering what the file path is to edit the main menu links. I just want to add one link and remove the "email" and "feed" links. 

Thanks

**Comment by xenocrat** [comment]
Hello there. You can edit the template file _themes/\[theme\]/layouts/default.twig_ to add or remove navigation links.

If the theme is Blossom or Topaz, you will also need to edit _content/sidebar.twig_. Those two themes show the sidebar when the browser window is wide enough, and the footer menu when the window is narrow.
