### ISSUE TITLE
Tumblr Import

### ISSUE THREAD

**Issue by mtech** [xenocrat/chyrp-lite#7]
I have a tumblr account I am trying to import from. When I type in my link, I get the following message...

Content could not be retrieved from the given URL. Server returned a message: HTTP/1.1 404 Not Found

My link to my tumblr page is valid. Not sure why it's throwing this error. Any ideas?

**Comment by xenocrat** [comment]
Are you using the latest sync of the develop branch? If so, I broke something. [Here's the fix](https://github.com/xenocrat/chyrp-lite/commit/084bc0e78314319e8d086880a9fd416ac3035919).

**Comment by mtech** [comment]
I was using the master branch. Sorry. I am uploading the develop branch now. Also, can you remove all the unnecessary files such as triggers and all in the develop branch if we aren't using them? No big deal, just a pet peeve of mine.

**Comment by xenocrat** [comment]
No worries, hope it's working ok for you now. I have done very little testing of the import scripts so please do let me know if you continue to see problems.

Most recent release has had a big purge and tidy up of support files, which have been moved to the [tools](https://github.com/xenocrat/chyrp-lite/tree/master/tools) folder. There is good reason for them to stay in the repo because they are valuable for extension development, but I agree they looked quite a mess in the root folder.

**Comment by mtech** [comment]
Awesome. The import for Tumblr worked flawlessly. Seems to be up to par now. Thanks again!

**Comment by kehugter** [comment]
I'm curious - which feather handles tumblr multi-image posts?

**Comment by kreativmind** [comment]
@kehugter Each feather is used depending on the type of Tumblr post. Have a look at the importer coding to understand better.
`                switch($post->attributes()->type) {
                    case "regular":
                        $title = fallback($post->regular_title);
                        $values = array("title" => $title,
                                        "body" => $post->regular_body);
                        $clean = sanitize($title);
                        break;
                    case "video":
                        $values = array("embed" => $post->video_player,
                                        "description" => fallback($post->video_caption));
                        break;
                    case "conversation":
                        $title = fallback($post->conversation_title);
                        $lines = array();
                        foreach ($post->conversation_line as $line)
                            $lines[] = $line->attributes()->label." ".$line;
                        $values = array("title" => $title,
                                        "body" => implode("<br>", $lines));
                        $clean = sanitize($title);
                        break;
                    case "photo":
                        $values = array("filename" => upload_from_url($post->photo_url[0]),
                                        "caption" => fallback($post->photo_caption));
                        break;
                    case "quote":
                        $values = array("quote" => $post->quote_text,
                                        "source" => preg_replace("/^&mdash; /", "",
                                                                 fallback($post->quote_source)));
                        break;
                    case "link":
                        $name = fallback($post->link_text);
                        $values = array("name" => $name,
                                        "source" => $post->link_url,
                                        "description" => fallback($post->link_description));
                        $clean = sanitize($name);
                        break;
                }`

**Comment by xenocrat** [comment]
Looks like it just takes the first photo from a Tumblr photo set. Chyrp Lite's Uploader feather can handle multiple images and displays them as a gallery, so I might rewrite this importer at some point in the future.

**Comment by kreativmind** [comment]
That's what I was going to say @xenocrat :-)
