### ISSUE TITLE
Options for Embedding Images?

### ISSUE THREAD

**Issue by millerjs2** [xenocrat/chyrp-lite#70]
I'm interested in knowing what options are available when embedding images - specifically when it comes to scaling them down. Right now it seems like chryp wants to blow them up to full size, and I'd like to have the ability to manually scale them to fit. Is this possible?

**Comment by xenocrat** [comment]
Images embedded using raw HTML or Markdown will be displayed at their native size or 100% article width, whichever is smaller. Images uploaded using the Photo or Uploader feathers will always be full width.

How images are displayed is controlled by the theme, so you would have to modify your theme's CSS or write some HTML to change the size of images on the blog. If you want to specify a unique non-native width per image, you must embed it using raw HTML in your post's body or description, like so:

    <img src="example.jpg" width="640">

If you just want to disable the theme's upscaling of smaller images, you can edit this CSS rule that is specified by all four built-in themes:

    article > section.photo img { width: 100% }

You can see the rule [here](https://github.com/xenocrat/chyrp-lite/blob/v2018.02/themes/blossom/stylesheets/all.css#L538) in Blossom's CSS. It makes Photo and Uploader images full width. If you remove that rule the images will be displayed at their native size or 100% width, whichever is smaller.

Lastly, if you are developing your own theme then you can use the image cacher to resize an image. Change the numbers in the `thumbnail` [filter](https://github.com/xenocrat/chyrp-lite/wiki/Twig-Reference#filters) (e.g. [here](https://github.com/xenocrat/chyrp-lite/blob/v2018.02/themes/blossom/feathers/photo.twig#L10)) to scale down a large image to a specific size.

I hope that helps!

**Comment by meskarune** [comment]
You can manually scale images on your desktop using image editing software. That is what I do for most web images anyways.

**Comment by meskarune** [comment]
@millerjs2 You might be interested in this project: http://phpthumb.sourceforge.net/ It is a php application that will do image resizing for you. Basically it is used like this:

    <img src="<path to php thumb>/phpThumb.php?src=images%2MYPIC.jpg&amp;w=300&h=300&....<rest of the options> alt="my pic" >

It works with the php gd library and image magick.
