### ISSUE TITLE
Broke my web site : database errors

### ISSUE THREAD

**Issue by supersophie** [xenocrat/chyrp-lite#71]
Hi,

I had an old version of chyrp that I failed to upgrade correctly a few months earlier.  I left it in a mess until the sqlite dB started growing ( no idea why ), and I shut that vhost down. 

Yesterday, I tried to resurrect this. I want to at least get the articles out, and then I can set up a new and empty version of chyrp.

But the site is too broken. Is there a way to extract the pages I wrote?  There were not many articles. Maybe ten. 

The web site throws this error:
Database Error

SQLSTATE[HY000]: General error: 26 file is encrypted or is not a database
SELECT sessions.data
FROM sessions
WHERE (sessions.id = :id)
ORDER BY sessions.id

Array
(
    [:id] => 8njo6rdeld65skcq3p2ot2fnb5
)

#0 /var/www/www.example.org/includes/class/Query.php(64): PDO->prepare('SELECT sessions...')
#1 /var/www/www.example.org/includes/class/SQL.php(220): Query->__construct(Object(SQL), 'SELECT sessions...', Array, false)
#2 /var/www/www.example.org/includes/class/SQL.php(257): SQL->query('SELECT sessions...', Array, false)
#3 /var/www/www.example.org/includes/class/Session.php(38): SQL->select('sessions', 'data', Array, 'id')
#4 [internal function]: Session::read('8njo6rdeld65skc...')
#5 /var/www/www.example.org/includes/helpers.php(37): session_start()
#6 /var/www/www.example.org/includes/common.php(317): session()
#7 /var/www/www.example.org/index.php(5): require_once('/var/www/www.ex...')
#8 {main}
                                        Log in

Any help appreciated. Sophie

**Comment by xenocrat** [comment]
That certainly is a mess. Last time we spoke you had a problem with a partially failed upgrade to v2015.06 (Saxaul) but your database seemed to be intact because you could browse your site, albeit in a broken state. What happened since then?

I would restore from a backup if you have one, or you could try [this](https://stackoverflow.com/questions/18259692/how-to-recover-a-corrupt-sqlite3-database) to salvage your database.

**Comment by supersophie** [comment]
Since then I left it alone. Then I noticed the dB growing in size. I saw a web crawler  hitting it , and regular errors in the logs (don't have them anymore I think). then I shut the site down. And now its like this. Quite odd.  
Yep, a mess.

**Comment by xenocrat** [comment]
It's worth checking your _config.json.php_ to ensure that it actually points to the database file:

    "database": "/absolute/path/to/sqlite.db",

Also check that the directory the database is located in is writable.

**Comment by supersophie** [comment]
Hi Daniel, 

Tried this and gained an empty dB :)
sqlite3 mydata.db ".dump" | sqlite3 new.db
The file exists as defined in config.json.php, and dir and file is writeable.

Opps.


Sophie

**Comment by supersophie** [comment]
Hi, I recovered the posts from the corrupted database reasonably well :)

. # strings chyrp_sqlite.db > chyrp_sqlite.txt
. # vi chyrp_sqlite.txt 

The posts were intact and could be copied and pasted into my new Chryp-lite installation.

**Comment by xenocrat** [comment]
I'm happy you found a way to do it. Please remember to make a backup. =)

**Comment by supersophie** [comment]
Backup made x 3 :)
