### ISSUE TITLE
Add postgresql support

### ISSUE THREAD

**Issue by krepver** [xenocrat/chyrp-lite#72]
Is it possible?

**Comment by xenocrat** [comment]
The short answer is no.

PostgreSQL is too different from MySQL and SQLite for this to be a simple implementation. It would require a significant amount of time and resources (two things I don't have enough of) to get PostgreSQL properly supported, and to test it for each new release.

**Comment by krepver** [comment]
Thank you for reply.

I have tried simple modifications for it, but got problem with datetime (timestamp in postgres) - it doesn't have operator "LIKE" with this type.
