### ISSUE TITLE
Can't export blog contents

### ISSUE THREAD

**Issue by vybhav93** [xenocrat/chyrp-lite#73]
Dear developer / experts,

I have upgraded to shelly version last month & i can't export data now. Error is 
tempnam(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): (/var/sentora/hostdata/maayaloka/public_html/:/var/sentora/temp/)

Pls help..

**Comment by xenocrat** [comment]
Hello there. It seems your PHP installation is configured with an `open_basedir` [setting](https://secure.php.net/manual/en/ini.core.php#ini.open-basedir) that is preventing Chyrp Lite from creating a temporary file in the server's designated temporary directory. This temporary file is needed to generate a ZIP archive containing your exported items.

You can see the line of code [here](https://github.com/xenocrat/chyrp-lite/blob/v2018.02/includes/controller/Admin.php#L1286).

There are two ways you can resolve this, depending on the level of control you have over the server:
1. Add the directive `sys_temp_dir` to the [_php.ini_](http://php.net/manual/en/ini.list.php) file for your PHP installation and point it to _/var/sentora/temp/_, which the error message indicates is an allowed path.
2. Modify the file _includes/controller/Admin.php_ at line 1286 and replace the text `sys_get_temp_dir()` with `"/var/sentora/temp/"`.

**Comment by vybhav93** [comment]
Thanks sir.. You helped me...
