### ISSUE TITLE
admin panel

### ISSUE THREAD

**Issue by TinosThemes** [xenocrat/chyrp-lite#77]
simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '<' not found

**Comment by xenocrat** [comment]
This might be the update checker not being able to open a socket and failing inelegantly. Can you modify this line of your file _includes/config.json.php_:

    "check_updates": true,

Change it to:

    "check_updates": false,

And let me know if the problem goes away.

**Comment by TinosThemes** [comment]
Great Work .... Perfect Solved
