### ISSUE TITLE
Support question : Themes - Stardust

### ISSUE THREAD

**Issue by supersophie** [xenocrat/chyrp-lite#79]
Hi, 

I have a theme called Stardust from Chyrp that I modified afterwards.  I copied it into the themes folder on Chyrp-Lite.  The Preview still shows the image, but running Preview gives an error of,

   Error : Unexpected "admin" tag (expecting closing tag for the "if" tag defined near line 23).

Does anybody have a working theme similar to the original Stardust? 

Thx, S

**Comment by xenocrat** [comment]
Chyrp themes won't work with Chyrp Lite because of extensive changes to the template engine. You can read more [in the wiki](https://github.com/xenocrat/chyrp-lite/wiki/Twig-Reference).

I am not aware of Stardust being updated for Chyrp Lite by anyone.

**Comment by supersophie** [comment]
Hi Daniel,

Best I stay away from the Stardust theme, for now.

Seems I broke the installation last night and only noticed this morning by unintentionally enabling the stardust theme. Thought I had previewed it only, which means the incompatible theme won’t load. Is there a place I can change the theme back to the default?  Else, I’ll re-install.

**Comment by supersophie** [comment]
Solved:
```$ cd themes 
```$ mv stardust/ stardust.off
```$ ln -s blossom stardust

In Admin->Extend->Themes set theme to Blossom.
Solved.

**Comment by xenocrat** [comment]
When you preview a theme, a value is set in your session so that you see the preview but all other visitors to your blog see it as normal. Clearing your session cookie would have been the quickest way to resolve this problem. Glad you found a solution!
