### ISSUE TITLE
Problems with Chyrp on localhost

### ISSUE THREAD

**Issue by Grazouillis** [xenocrat/chyrp-lite#80]
Hello,

Thank you for this nice CMS, I like it !

I noticed two problems with Chyrp local testing : 

I observe an Invalid Chyrp URL error.
`var_dump($_POST['url']);` => http://localhost/chyrp -> this URL is considered as invalid because there is no extension, I suppose.

So we need to comment 496-497 lines to continue.

Install.php 
```
        elseif (!is_url($_POST['url']))
            $errors[] = __("Invalid Chyrp URL.");
```

When I try to create post with the manager, I get this another error on the front-end : 

Error -- count(): Parameter must be an array or an object that implements Countable

(I didn't analyze that error and its reason.)

Regards,
Reka

**Comment by xenocrat** [comment]
I wouldn't advise this. It breaks URL detection across all of Chyrp Lite, when instead you could just use 127.0.0.1 or your local IP address for testing purposes.

**Comment by xenocrat** [comment]
Good solution. Thank you for documenting it!
