### ISSUE TITLE
Any ways to make chyrp search "pages"?

### ISSUE THREAD

**Issue by Dextrolain** [xenocrat/chyrp-lite#82]
Hi.
I was wondering if there is an easy way to make chyrp search among "pages" too? Not only "posts" .
If not, it would be cool to see this enhancement in some future updates :)

**Comment by xenocrat** [comment]
Hello there. Currently the only way to do it would be creating a module to overload the search function and use an alternate search engine. I will keep it noted as a potential enhancement. Thanks for the suggestion!

**Comment by xenocrat** [comment]
As of version 2020.04, it is possible to include pages in search results.
