### ISSUE TITLE
Custom twig static page

### ISSUE THREAD

**Issue by giodum** [xenocrat/chyrp-lite#86]
Hi, I love Chyrp Lite and I am thinking about using it for my personal blog.
I am trying to add a custom twig page and link it in the main menu.

I create my `custompage.twig` inside the pages folder of the theme. Then in the `default.twig` I add  a new link with `{{ url('/custompage') }}` but when I click on the link it gives me an error message "The requested resource was not found."

I think I should set a route or something similar. How can I solve the problem?

Thanks very much

**Comment by xenocrat** [comment]
Hello there. Every page that Chyrp Lite serves must be the result of a successful [routing process](https://github.com/xenocrat/chyrp-lite/wiki/Routes-and-Controllers), and the routing process is not designed to discover static content stored in theme files. There is a "correct" and a hacky way to achieve what you want to do.

The hacky way:
1. Publish a page (Admin > Write > Page) with the slug "custompage" – the content is not important.
2. That's it!

Pages support a custom template file named after the page's slug. So now when you visit _/custompage_ the routing process will discover a valid page named "custompage" to display and it will use your "custompage" template file to do so. Your template file will be supplied with the page object but it can display whatever it chooses to the visitor.

The "correct" way:
1. [Create a module](https://github.com/xenocrat/chyrp-lite/wiki/Making-Your-First-Module) – its name is not important.
2. Add this function to your module:

        public function main_custompage($main) {
            $main->display("pages".DIR."custompage");
        }

3. Enable your module.

Now the module will act as a responder to the "custompage" route. Your module could do all kinds of things as a route responder, but all it does in this case is display a twig file containing your static content. With this method, the name of the twig file is not important, it's the name of the function (`main_custompage`) that determines what URL will display your page to visitors.

The dirty URL differs depending on which option you choose, but if you have clean URLs enabled your page can be reached at _/custompage_  in both cases. I hope that helps!
