### ISSUE TITLE
broken image link with clean URLs

### ISSUE THREAD

**Issue by rytis-paskauskas** [xenocrat/chyrp-lite#88]
version 2019.02

Hi,
To reproduce the issue following a clean install: 
- import an image `img.jpg`
- link to it in a page like so `![text](uploads/img.jpg)` 
- then go to Settings -> Routes  and tick clean URLs
- return to the main page - the link to the image is broken!
- return to settings, untick clean URLs
- return to the main page - the image is back!

Sorry that I can't provide more technical clues... unless you tell me how.

**Comment by xenocrat** [comment]
Hello there. If you use a relative URL in your image links, the web browser will use the current page URL to determine the absolute path to the image. When you enable clean URLs, relative image links will be interpreted incorrectly by the web browser. Like so:

Image link:
`![text](uploads/img.jpg)`

Dirty URL:
`http://example.com/chyrp/?action=view&url=broken-link`

Clean URL:
`http://example.com/chyrp/2019/06/05/broken-link/`

Relative image path with dirty URL:
`http://example.com/chyrp/uploads/img.jpg`

Relative image path with clean URL:
`http://example.com/chyrp/2019/06/05/broken-link/uploads/img.jpg`

The solution is always to use absolute URLs for your image links:
`![text](http://example.com/chyrp/uploads/img.jpg)`

I hope that helps!

**Comment by rytis-paskauskas** [comment]
that helps, thank you very much!

Will using absolute URLs result in a DNS lookup related overhead with respect to local URLs?

**Comment by xenocrat** [comment]
No difference to network activity, it's just a question of when and how the URL is made absolute.
