### ISSUE TITLE
Edit menu items (Umbra)

### ISSUE THREAD

**Issue by markx2** [xenocrat/chyrp-lite#89]
Goal: to remove all menu links apart from Search

/themes/umbra/layouts/default.twig

Remove lines between and including
`<ul role="menubar" class="navigation">` (line 36)
to
`</ul>` (line 76)

Save this change, but on reload the site remains the same.

I have confirmed that the file on the server does not have the code in it.
I have no caching set
The theme has no sidebar.twig

Am I missing something obvious? Thanks

**Comment by xenocrat** [comment]
Hello there. Twig is probably using an old cache of the template file, which is why you are not seeing the changes you made. You can reset the cache by deleting the contents of the directory _/includes/caches/twig/_.

**Comment by markx2** [comment]
Perfect! Thank you.

I did not realise that Twig was caching, so this was a useful TIL for me.
