### ISSUE TITLE
Activating Recaptcha in Kordofan

### ISSUE THREAD

**Issue by mtech** [xenocrat/chyrp-lite#9]
Missing argument 1 for recaptcha_get_html(), called in /mysite/modules/recaptcha/recaptcha.php on line 52 and defined (/mysite/modules/recaptcha/lib/recaptchalib.php on line 106)

Backtrace

modules/recaptcha/lib/recaptchalib.php on line 106
modules/recaptcha/recaptcha.php on line 52
includes/helpers.php on line 1737
includes/controller/Main.php on line 804
includes/controller/Main.php on line 763
includes/controller/Main.php on line 432
includes/class/Route.php on line 122
includes/class/Route.php on line 122

**Comment by xenocrat** [comment]
Oops! [Here's](https://github.com/xenocrat/chyrp-lite/commit/81afef0b354e3146f3391deecd74f7d516bbaaeb) the fix. If you patch your site with that updated file, or just copy the missing variable name into your current version of `recaptcha.php`, that should solve it.

Thanks for the report!

**Comment by mtech** [comment]
I fixed the file. Thanks!

**Comment by mtech** [comment]
Closing issue since it's been fixed. Thanks again D!
