### ISSUE TITLE
Tags page error

### ISSUE THREAD

**Issue by henning-bertram** [xenocrat/chyrp-lite#92]
Hi.

I have seen this error earlier, but updated to Eurasian before I reported. It is still there.

 If I go to a tags page, I get this error (in the log):

12-Aug-2019 07:28:10 UTC] ERROR: 2 htmlspecialchars() expects parameter 1 to be string, array given (/var/
www/html/bertramonline.com/public_html/includes/helpers.php on line 1067)

(An example would be https://bertramonline.com/tag/culture/)

I have no weird characters in tags and so forth. But I am running on PHBP 7.3.

**Comment by xenocrat** [comment]
Hello there. I really need to see a backtrace to help me resolve this issue. You can find instructions for enabling DEBUG mode [here on the wiki](https://github.com/xenocrat/chyrp-lite/wiki/Debug-and-Tester-Modes), which will cause a backtrace to be displayed on error pages.

**Comment by henning-bertram** [comment]
Did it. Same URL shows the full trace.

**Comment by xenocrat** [comment]
Thanks. It looks like the error is being triggered by your theme. Take a look at your theme's _tags.twig_ file and compare it to the [_tags.twig_](https://github.com/xenocrat/chyrp-lite/blob/master/themes/blossom/pages/tag.twig#L6) for the Blossom theme, especially any lines that deal with outputting the tag name.

**Comment by henning-bertram** [comment]
That was it - my very old theme had "tag" instead of "tag.name". Thanks.
