### ISSUE TITLE
Longer list of needed php extensions in documentation.

### ISSUE THREAD

**Issue by jpalczewski** [xenocrat/chyrp-lite#98]
Hi,

I have recently successfully installed chyrp-lite on fresh alpine installation and falled  into "module needed but not installed" errors, so that might be worthwhile to include in docs that following modules are necessary:

- php7-session - error in logs after first visit on install.php 
- php7-json - fatal error after proceeding with installation
- php7-ctype - twig error after installation
- php7-xml - fatal error on first visit in admin panel

That's not an extensive list, but all of those are required in basic workflow.

**Comment by xenocrat** [comment]
Hello there.

Thanks for the report. I rely only on modules that are usually enabled by default, but the modular nature of PHP means the defaults cannot always be relied on. I will consider noting in the docs that Chyrp Lite assumes a default PHP installation.
