### ISSUE TITLE
Clean URL not working on nginx

### ISSUE THREAD

**Issue by jpalczewski** [xenocrat/chyrp-lite#99]
Hi again,

This time i has bad time with trying to enabling and  fixing the clean url mode - despite all changes(break to last in include conf, etc) nginx suggests to download  all files in /admin/*, where clean /admin works(locking out option to disable it, so editing conf.json.php is necessary in order to disable it)

rest of mine nginx conf is rather fresh version of https://www.digitalocean.com/community/tools/nginx.

**Comment by xenocrat** [comment]
Hello there.

The Nginx configuration is entirely untested, so thank you for being the first tester! I understand you had problems with the conf but from your description I don't quite understand what went wrong. Please could you give an example?

**Comment by jpalczewski** [comment]
1. Lets start with  `$baseurl/admin`, where admin menu loads nicely and clean url option is enabled.
2. We want to go somewhere else in admin page, f.e another tab
3. Step above ends in download dialog being shown, where downloaded file content is a php file, possibly` admin/index.php`.

As I was trying to explain in twisted way before - https://serverfault.com/questions/536859/my-nginx-rewrite-is-downloading-the-php-file - I tried that way with changing from break to last in location rules, but without success. So the problem is somewhere between rewrite rule and possibly then nginx ignores another rules and treat `admin/index.php` a as regular file.

I might give it another try to confirm that bug soon, but I'll hapilly test any future suggestions.

**Comment by xenocrat** [comment]
Thank you for the description, that's very clear now. I will take a closer look at this problem. In the meantime, [this solution](https://stackoverflow.com/a/42686936) might be worth trying.

**Comment by xenocrat** [comment]
I have another suggestion. Try including Chyrp Lite's _include,conf_ above the directive `# index.php fallback` in _example.com.conf_. It would look something like this:

	include path/to/chyrp/include.conf;
	
	# index.php fallback
	location / {
		try_files $uri $uri/ /index.php?$query_string;
	}
	
	# handle .php
	location ~ \.php$ {
		include nginxconfig.io/php_fastcgi.conf;
	}

This will ensure that the URL is rewritten to _path/to/chyrp/index.php_ before ngnix encounters the directive `# handle .php`. I believe the `break` flags in Chyrp Lite's directives are the correct thing to do, to avoid an infinite loop in location matching.

**Comment by jpalczewski** [comment]
Including directly `include.conf` before `location /`  won't work because nginx refuse to start with that configuration
```
nginx: [emerg] duplicate location "/" in /etc/nginx/sites-enabled/redacted.example.com.conf:24
nginx: configuration file /etc/nginx/nginx.conf test failed
```
So, I have merged both locations for testing:
```
	location / {
		rewrite \.twig$ /index.php break;

		if (-f $request_filename) {
			break;
		}

		if (-d $request_filename) {
			break;
		}

		rewrite ^/admin/.+ /admin/index.php break;
		rewrite ^.+$ /index.php break;

		try_files $uri $uri/ /index.php?$query_string;

	}


	# handle .php
	location ~ [^/]\.php(/|$) {
		include nginxconfig.io/php_fastcgi.conf;
	}
```
And now -
- / and /admin location works
- Settings and Extends tab returns following text(due to solution that you mentioned earlier):  `init(); $trigger->call("end", $route); ob_end_flush(); ` Actually this behaviour applies also to /foo and /bar locations
- Exception is /admin/manage/ cause it behaves in _old_ way - returns octet-stream ffile  with following content:
```php
<?php
    define('ADMIN', true);

    require_once dirname(dirname(__FILE__)).DIRECTORY_SEPARATOR."includes".DIRECTORY_SEPARATOR."common.php";

    # Prepare the controller.
    $admin = AdminController::current();

    # Parse the route.
    $route = Route::current($admin);

    # Respond to the request.
    $route->init();

    $trigger->call("end", $route);

```
- AFAIR I tested both ways(index after and before location block) with  rather doesn't impact in any way. 

For the record: this time I'm running on origin/master where last time was last release.

**Comment by xenocrat** [comment]
So it looks as if the rewrite is working exactly as intended, but then Nginx serves the PHP file without preprocessing it. How bizarre. 

If / and /admin locations work, maybe `try_files` is needed to trigger the PHP preprocessor.

Let's try this:

	location / {
		if ($uri ~ \.twig$) {
			try_files /index.php;
			break;
		}

		if (-f $request_filename) {
			break;
		}

		if (-d $request_filename) {
			break;
		}

		if ($uri ~ ^/admin/.+) {
			try_files /admin/index.php$is_args$args;
			break;
		}

		if ($uri ~ ^.+$) {
			try_files /index.php$is_args$args;
			break;
		}
	}

**Comment by xenocrat** [comment]
After further reading, I've tried to improve the snippet a bit:

	location / {
		index index.php;
		rewrite \.twig$ /index.php
	
		if ($uri ~ ^/admin/.+) {
			try_files $uri $uri/ /admin/index.php;
		}
	
		try_files $uri $uri/ /index.php;
	}

**Comment by jpalczewski** [comment]
Your last solution after a bit of improvement works:

```nginx
location / {
		
	index index.php;
	rewrite \.twig$ /index.php;

	location  ^~ /admin/ {
		try_files $uri $uri/ /admin/index.php;
	}

	try_files $uri $uri/ /index.php;
	}
```
Word of explaination:  nginx wants rather only one try_files per location block where if is the same content(unlike the nested location). 
As it works on my instance I think that I can happily close this issue and mark the problem as solved.

**Comment by xenocrat** [comment]
Thank you for your patience and help. I will update the nginx.conf template for the next release.
